import { expect, test } from '@playwright/test';
const config = {ok:true,comparison:{enabled:true,assets:['base_usdc','solana_usdc']},actions:{deploy:true,return:true,send:true},zec_price:{usd_micros:'100000000',observed_at:new Date().toISOString()},assets:[{key:'solana_usdc',label:'Solana · USDC',symbol:'USDC',supported:true},{key:'base_usdc',label:'Base · USDC',symbol:'USDC',supported:true}]};
const quote=()=>({available:true,destination_amount:'499.1',destination_symbol:'USDC',source_amount:'5',source:'zec',destination_location:'sol',input_usd_micros:'500000000',minimum_destination_amount:'494.109',estimated_settlement_seconds:452,all_in_marked_friction_ppm:'1800',trust:{provider_signature_verified:true},fee_components:{provider_injected_app_fee_bps:10},privacy:{timing_correlation_risk:'high',amount_correlation_risk:'high'},quote_latency_ms:3200,research_expires_at:new Date(Date.now()+30000).toISOString(),observed_at:new Date().toISOString()});
async function fixture(page,{pro=true,authenticated=true,delay=0}={}) {
 const calls=[];
 await page.route('**/api/v1/auth/session',r=>r.fulfill({json:{ok:true,authenticated,csrf_token:authenticated?'fixture':null}}));
 await page.route('**/api/v1/portfolio/shielded',r=>r.fulfill({status:pro?200:403,json:pro?config:{ok:false,error:'pro_required'}}));
 await page.route('**/api/v1/portfolio/shielded/quote',async r=>{calls.push(r.request().postDataJSON());expect(r.request().headers()['x-ravenos-csrf']).toBe('fixture');if(delay)await new Promise(resolve=>setTimeout(resolve,delay));await r.fulfill({json:{ok:true,quote:quote()}});});
 return calls;
}
for(const [name,size] of [['desktop',{width:1440,height:1100}],['mobile',{width:390,height:844}]])test(`reserve ${name} renders a real preview boundary and stays inside viewport`,async({page})=>{
 await page.setViewportSize(size);const errors=[];page.on('pageerror',e=>errors.push(e.message));const calls=await fixture(page);await page.goto('/portfolio/#shielded-reserve');await expect(page.locator('#reserveTools')).toBeVisible();expect(calls).toHaveLength(0);await expect(page.locator('.reserve-capital-strip')).toContainText('Not integrated yet');await page.getByRole('button',{name:'Preview deployment',exact:true}).click();await expect(page.locator('#reserveReceive')).toHaveText('499.1 USDC');await page.getByText('Inspect privacy & route evidence',{exact:true}).click();await expect(page.locator('#reserveEvidence')).toContainText('Unknown · no shielded settlement proof');expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(2);await page.locator('#shielded-reserve').screenshot({path:test.info().outputPath(`reserve-${name}.png`)});expect(errors).toEqual([]);
});
test('local planner never calls provider and Copy shortfall remains separate from reserve',async({page})=>{const calls=await fixture(page);await page.goto('/portfolio/');await expect(page.locator('#reserveTools')).toBeVisible();await page.getByText('Plan your working capital',{exact:true}).click();await page.locator('#reservePlanZec').fill('76');await page.locator('#reservePlanWorking').fill('2400');await page.locator('#reservePlanTarget').fill('5000');await page.locator('#reservePriceMove').selectOption('-30');await page.getByRole('button',{name:'Calculate scenario'}).click();await expect(page.locator('#reservePlanResult')).toContainText('$5,320.00');await expect(page.locator('#reservePlanResult')).toContainText('2,600.00 USDC');expect(calls).toHaveLength(0);await page.locator('#reservePlanWorking').fill('13200');await page.locator('#reservePlanTarget').fill('10000');await page.getByRole('button',{name:'Calculate scenario'}).click();await page.getByRole('button',{name:'Preview return of excess'}).click();await expect(page.locator('#reserveAmount')).toHaveValue('3200.00');expect(calls).toHaveLength(0);await expect(page.locator('[data-reserve-action=SHIELDED_RETURN]')).toHaveAttribute('aria-pressed','true');});
test('changing route discards late result from previous preview',async({page})=>{await fixture(page,{delay:500});await page.goto('/portfolio/');await expect(page.locator('#reserveTools')).toBeVisible();await page.getByRole('button',{name:'Preview deployment'}).click();await page.getByRole('button',{name:'Return',exact:true}).click();await page.waitForTimeout(600);await expect(page.locator('#reserveQuote')).toBeHidden();await expect(page.locator('#reserveQuoteButton')).toHaveText('Preview return');});
for(const type of ['Standard','signed out'])test(`${type} cannot use Pro quote form`,async({page})=>{const calls=await fixture(page,{pro:type!=='Standard',authenticated:type!=='signed out'});await page.goto('/portfolio/');await expect(page.locator('#reserveAccount')).toBeVisible();await expect(page.locator('#reserveTools')).toBeHidden();expect(calls).toHaveLength(0);});
test('expired preview is visibly historical and never becomes a submit button',async({page})=>{await fixture(page);await page.route('**/api/v1/portfolio/shielded/quote',r=>r.fulfill({json:{ok:true,quote:{...quote(),research_expires_at:new Date(Date.now()-1000).toISOString()}}}));await page.goto('/portfolio/');await expect(page.locator('#reserveTools')).toBeVisible();await page.getByRole('button',{name:'Preview deployment'}).click();await expect(page.locator('#reserveQuoteState')).toHaveText('PREVIEW EXPIRED');await expect(page.locator('#reserveFreshness')).toContainText('Request a fresh route');await expect(page.getByRole('button',{name:/sign|execute|confirm/i})).toHaveCount(0);});
const comparison = () => { const q={...quote(),quote_hash:'verified-test-evidence',privacy:{...quote().privacy,classification:'UNKNOWN'}}; return {available:true,source:'base_usdc',destination:'solana_usdc',research_expires_at:q.research_expires_at,direct:{...q,destination_amount:'499',privacy:{classification:'PUBLIC'},estimated_settlement_seconds:32},reserve:{return:{...q,destination_amount:'4.98',destination_symbol:'ZEC'},deploy:q,estimated_receive:'497',provider_time_sum_seconds:602,all_in_marked_friction_ppm:'6000'}}; };
for(const [name,size] of [['desktop',{width:1440,height:1100}],['mobile',{width:390,height:844}]])test(`reserve comparison ${name} shows both legs without promising settlement`,async({page})=>{
 await page.setViewportSize(size);const calls=await fixture(page);const comparisons=[];
 await page.route('**/api/v1/portfolio/shielded/compare',async r=>{comparisons.push(r.request().postDataJSON());expect(r.request().headers()['x-ravenos-csrf']).toBe('fixture');await r.fulfill({json:{ok:true,comparison:comparison()}});});
 await page.goto('/portfolio/');await expect(page.locator('#reserveTools')).toBeVisible();await expect(page.locator('.reserve-stage-note')).toContainText('transfers and recovery are not available');
 await page.getByText('Compare direct vs reserve routes',{exact:true}).click();expect(comparisons).toHaveLength(0);
 await page.getByRole('button',{name:'Compare routes',exact:true}).click();await expect(page.locator('#reserveCompareDirect')).toContainText('499 USDC');await expect(page.locator('#reserveCompareShielded')).toContainText('497 USDC');await expect(page.locator('#reserveCompareShielded')).toContainText('Not guaranteed');await expect(page.locator('#reserveCompareShielded')).toContainText('+ wallet wait');
 expect(comparisons).toEqual([{source:'base_usdc',destination:'solana_usdc',amount_usd:'500'}]);expect(calls).toHaveLength(0);
 await page.getByText('Inspect comparison evidence',{exact:true}).click();await expect(page.locator('#reserveCompareEvidence')).toContainText('UNKNOWN');await expect(page.locator('#reserveCompareEvidence')).toContainText('Return to reserve');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(2);
 await page.locator('#reserveComparison').screenshot({path:process.env.RAVENOS_VISUAL_ARTIFACT_DIR?`${process.env.RAVENOS_VISUAL_ARTIFACT_DIR}/reserve-comparison-${name}.png`:test.info().outputPath(`comparison-${name}.png`)});
 await page.locator('#reserveCompareAmount').fill('100');await expect(page.locator('#reserveCompareResult')).toBeHidden();
});
test('comparison validates distinct networks and suppresses a late result after input changes',async({page})=>{
 await fixture(page);let count=0;await page.route('**/api/v1/portfolio/shielded/compare',async r=>{count++;await new Promise(resolve=>setTimeout(resolve,500));await r.fulfill({json:{ok:true,comparison:comparison()}});});
 await page.goto('/portfolio/');await expect(page.locator('#reserveTools')).toBeVisible();await page.getByText('Compare direct vs reserve routes',{exact:true}).click();
 await page.locator('#reserveCompareDestination').selectOption('base_usdc');await page.getByRole('button',{name:'Compare routes',exact:true}).click();await expect(page.locator('#reserveCompareStatus')).toContainText('different networks');expect(count).toBe(0);
 await page.locator('#reserveCompareDestination').selectOption('solana_usdc');await page.getByRole('button',{name:'Compare routes',exact:true}).click();await page.locator('#reserveCompareAmount').fill('100');await page.waitForTimeout(600);await expect(page.locator('#reserveCompareResult')).toBeHidden();
});
test('comparison expiry is explicit and errors cannot display a partial success',async({page})=>{
 await fixture(page);await page.route('**/api/v1/portfolio/shielded/compare',r=>r.fulfill({json:{ok:true,comparison:{...comparison(),research_expires_at:new Date(Date.now()-1000).toISOString()}}}));
 await page.goto('/portfolio/');await expect(page.locator('#reserveTools')).toBeVisible();await page.getByText('Compare direct vs reserve routes',{exact:true}).click();await page.getByRole('button',{name:'Compare routes',exact:true}).click();await expect(page.locator('#reserveCompareFreshness')).toHaveText('PREVIEWS EXPIRED');
 await page.route('**/api/v1/portfolio/shielded/compare',r=>r.fulfill({json:{ok:true,comparison:{available:false,reason:'provider_quote_rejected'}}}));await page.getByRole('button',{name:'Compare routes',exact:true}).click();await expect(page.locator('#reserveCompareResult')).toBeHidden();await expect(page.locator('#reserveCompareStatus')).toContainText('could not quote');
});
