import test from "node:test";
import assert from "node:assert/strict";
import { sqliteStore } from "./customer_pro_rewards.test.mjs";
import { CustomerLegalDocuments } from "../lib/customer_legal_registry.mjs";
import { createD1CustomerIdentityStore } from "../lib/customer_identity.mjs";
import { enrollAffiliate, activeAffiliateLink, captureReferralClick, lockSignupReferral, affiliateDashboard, reconcileAffiliateInvoice, affiliateBalance, recordAffiliateManualAction, commissionCents, addUtcMonths } from "../lib/customer_referral_growth.mjs";
import { affiliatePolicy } from "../lib/customer_product.mjs";
import { ensureProTrial } from "../lib/customer_pro.mjs";
const NOW=1788739200,AFF="usr_"+"a".repeat(32),STATE="c".repeat(64);
async function fixture({acceptTerms=true}={}) {
 const db=sqliteStore();
 db.raw.prepare("INSERT INTO ravenos_users (user_id,state,primary_email,username,created_at,updated_at,last_authenticated_at) VALUES (?,'active',?,'northstar',?,?,?)").run(AFF,"affiliate@example.test",NOW-60,NOW-60,NOW-60);
 const env={RAVENOS_CUSTOMER_DB:db,RAVENOS_REFERRALS_ENABLED:"1",RAVENOS_AFFILIATE_ENROLLMENT_ENABLED:"1",RAVENOS_AFFILIATE_COMMISSIONS_ENABLED:"1",RAVENOS_PRO_FREE_TRIAL_ENABLED:"1",RAVENOS_AUTH_HASH_PEPPER:"fixture-trial-identity-pepper"};
 if(acceptTerms) {const doc=CustomerLegalDocuments.find(d=>d.document_type==="affiliate_terms");db.raw.prepare("INSERT INTO ravenos_legal_acceptances (acceptance_id,user_id,document_type,document_version,content_hash,acknowledgement,accepted_at,acceptance_method) VALUES (?,?,'affiliate_terms',?,?,'agreed',?,'affiliate_enrollment')").run("lac_"+"a".repeat(32),AFF,doc.version,doc.content_hash,NOW);}
 return {db,env};
}
export async function referredFixture() {
 const f=await fixture(); const dashboard=await enrollAffiliate(f.env,AFF,{now:NOW});
 const click=await captureReferralClick(f.env,new Request("https://ravenos.xyz/r/northstar"),"northstar",{now:NOW});
 await lockSignupReferral(f.env,new Request("https://app.ravenos.xyz/api/v1/auth/start",{headers:{cookie:click.set_cookie.split(";")[0]}}),STATE,{now:NOW+1});
 const store=createD1CustomerIdentityStore(f.db);
 const identity={issuer:"https://api.workos.com",provider_subject:"referred_verified",email:"new@example.test",display_name:null,authentication_method:"GoogleOAuth",now:NOW+2};
 const account=await store.resolveOrCreateIdentity(identity,{referralStateHash:STATE});
 return {...f,dashboard,click,account,identity};
}
export function paidInvoice(f,{id="in_first123",day=40,cash=14900,credit=14900-cash,ref="evt_first123",sub="sub_first123"}={}) {
 const time=NOW+day*86400;
 const proof={verified:true,invoice_id:id,external_paid_cents:cash,source_reference:ref};
 f.db.raw.prepare(`INSERT INTO ravenos_pro_invoices (invoice_id,user_id,stripe_subscription_id,gross_cents,reward_credit_cents,external_paid_cents,currency,status,period_start,period_end,updated_at,paid_at,payment_evidence_json) VALUES (?,?,?,14900,?,?,'usd','paid',?,?,?,?,?)
 ON CONFLICT(invoice_id) DO UPDATE SET external_paid_cents=excluded.external_paid_cents,payment_evidence_json=excluded.payment_evidence_json,updated_at=excluded.updated_at`).run(id,f.account.user_id,sub,credit,cash,time,time+30*86400,time,time,JSON.stringify(proof));
 return id;
}
test("joining requires explicit current Affiliate Terms acceptance",async()=>{const f=await fixture({acceptTerms:false});await assert.rejects(enrollAffiliate(f.env,AFF,{now:NOW}),/terms_acceptance_required/);assert.equal(f.db.raw.prepare("SELECT COUNT(*) n FROM ravenos_referral_codes").get().n,0);});
test("referral vanity and stable code resolve the same active affiliate",async()=>{const f=await fixture();const joined=await enrollAffiliate(f.env,AFF,{now:NOW});assert.match(joined.referral_url,/\/r\/northstar$/);assert.equal((await activeAffiliateLink(f.db,joined.referral_code)).user_id,AFF);});
test("username changes do not break stable codes or prior vanity links",async()=>{const f=await fixture();const joined=await enrollAffiliate(f.env,AFF,{now:NOW});f.db.raw.prepare("UPDATE ravenos_users SET username='newstar' WHERE user_id=?").run(AFF);assert.equal((await activeAffiliateLink(f.db,joined.referral_code)).user_id,AFF);assert.equal((await activeAffiliateLink(f.db,"northstar")).username,"newstar");});
test("first click is captured once and subsequent clicks do not replace it",async()=>{const f=await referredFixture();const again=await captureReferralClick(f.env,new Request("https://ravenos.xyz/r/northstar",{headers:{cookie:f.click.set_cookie.split(";")[0]}}),"northstar",{now:NOW+10});assert.equal(again.click_id,f.click.click_id);assert.equal(f.db.raw.prepare("SELECT COUNT(*) n FROM ravenos_referral_clicks").get().n,1);});
test("signup attribution is committed server-side with the account and survives cookies",async()=>{const f=await referredFixture();const row=f.db.raw.prepare("SELECT * FROM ravenos_referral_attributions").get();assert.equal(row.referred_user_id,f.account.user_id);assert.equal(row.referrer_user_id,AFF);assert.equal(f.db.raw.prepare("SELECT attribution_expires_at FROM ravenos_referral_conversion_windows").get().attribution_expires_at,NOW+60*86400);});
test("referred accounts get exactly the normal no-card trial and no commission",async()=>{const f=await referredFixture();const trial=await ensureProTrial(f.env,{...f.account,state:"active"},{...f.identity,verified:true},{now:NOW+2});assert.equal(trial.state,"PRO_TRIAL_ACTIVE");assert.equal(trial.trial.trial_ends_at-trial.trial.trial_started_at,30*86400);assert.equal(trial.trial.card_required,false);assert.equal((await affiliateBalance(f.db,AFF)).earned_cents,"0");assert.equal(f.db.raw.prepare("SELECT COUNT(*) n FROM ravenos_pro_subscriptions").get().n,0);});
test("25 percent of 149 dollars is 37.25 and 12 continuous full months total 447",()=>{assert.equal(commissionCents("14900"),"3725");assert.equal(BigInt(commissionCents("14900"))*BigInt(affiliatePolicy().commission_months),44700n);assert.equal(commissionCents("1"),"0");});
test("day 40 voluntary paid conversion starts a 12-calendar-month commission window",async()=>{const f=await referredFixture();const invoice=paidInvoice(f);const r=await reconcileAffiliateInvoice(f.env,invoice,{now:NOW+40*86400});assert.equal(r.commission_cents,"3725");const window=f.db.raw.prepare("SELECT * FROM ravenos_referral_conversion_windows").get();assert.equal(window.paid_conversion_at,NOW+40*86400);assert.equal(window.commission_ends_at,addUtcMonths(window.paid_conversion_at,12));});
test("a positive payment starts the original window even when commission rounds below one cent",async()=>{
 const f=await referredFixture();
 const invoice=paidInvoice(f,{cash:1});
 assert.equal((await reconcileAffiliateInvoice(f.env,invoice)).state,"commission_below_cent");
 assert.equal((await affiliateBalance(f.db,AFF)).earned_cents,"0");
 const before=f.db.raw.prepare("SELECT * FROM ravenos_referral_conversion_windows").get();
 assert.equal(before.paid_conversion_at,NOW+40*86400);
 await reconcileAffiliateInvoice(f.env,paidInvoice(f,{id:"in_later123",day:70}));
 assert.equal(f.db.raw.prepare("SELECT commission_ends_at FROM ravenos_referral_conversion_windows").get().commission_ends_at,before.commission_ends_at);
 assert.equal(f.db.raw.prepare("SELECT COUNT(*) n FROM ravenos_product_events WHERE event_type='referral_paid_conversion'").get().n,1);
});
test("conversion after the 60-day attribution expiry does not earn commission",async()=>{const f=await referredFixture();const invoice=paidInvoice(f,{day:61});assert.equal((await reconcileAffiliateInvoice(f.env,invoice)).state,"attribution_expired");assert.equal((await affiliateBalance(f.db,AFF)).earned_cents,"0");});
test("rewards reducing new external payment to 100 dollars yield 25 dollars commission",async()=>{const f=await referredFixture();const invoice=paidInvoice(f,{cash:10000});assert.equal((await reconcileAffiliateInvoice(f.env,invoice)).commission_cents,"2500");});
test("a fully reward-funded month earns zero but preserves an existing commission window",async()=>{const f=await referredFixture();await reconcileAffiliateInvoice(f.env,paidInvoice(f));const before=f.db.raw.prepare("SELECT * FROM ravenos_referral_conversion_windows").get();assert.equal((await reconcileAffiliateInvoice(f.env,paidInvoice(f,{id:"in_second123",day:70,cash:0}))).state,"zero_qualifying_revenue");await reconcileAffiliateInvoice(f.env,paidInvoice(f,{id:"in_third123",day:100,cash:14900}));assert.equal((await affiliateBalance(f.db,AFF)).earned_cents,"7450");assert.equal(f.db.raw.prepare("SELECT commission_ends_at FROM ravenos_referral_conversion_windows").get().commission_ends_at,before.commission_ends_at);});
test("cancel and resubscribe never restart the first commission window",async()=>{const f=await referredFixture();await reconcileAffiliateInvoice(f.env,paidInvoice(f));const start=f.db.raw.prepare("SELECT paid_conversion_at FROM ravenos_referral_conversion_windows").get().paid_conversion_at;await reconcileAffiliateInvoice(f.env,paidInvoice(f,{id:"in_resume123",day:150,sub:"sub_resumed123"}));assert.equal(f.db.raw.prepare("SELECT paid_conversion_at FROM ravenos_referral_conversion_windows").get().paid_conversion_at,start);assert.equal((await reconcileAffiliateInvoice(f.env,paidInvoice(f,{id:"in_late123",day:410}))).state,"commission_window_ended");});
test("webhook retries and simultaneous invoice processing earn once",async()=>{const f=await referredFixture();const invoice=paidInvoice(f);await Promise.all([reconcileAffiliateInvoice(f.env,invoice,{source_reference:"evt_retry_1"}),reconcileAffiliateInvoice(f.env,invoice,{source_reference:"evt_retry_2"})]);await reconcileAffiliateInvoice(f.env,invoice);assert.equal((await affiliateBalance(f.db,AFF)).earned_cents,"3725");});
test("unpaid and fabricated revenue events cannot create commissions",async()=>{const f=await referredFixture();assert.equal((await reconcileAffiliateInvoice(f.env,"in_missing123")).state,"no_verified_paid_subscription");const invoice=paidInvoice(f);f.db.raw.prepare("UPDATE ravenos_pro_invoices SET payment_evidence_json=NULL WHERE invoice_id=?").run(invoice);assert.equal((await reconcileAffiliateInvoice(f.env,invoice)).state,"no_verified_paid_subscription");});
test("payment refund appends a commission reversal",async()=>{const f=await referredFixture();const invoice=paidInvoice(f);await reconcileAffiliateInvoice(f.env,invoice);paidInvoice(f,{cash:0,ref:"evt_refund123"});assert.equal((await reconcileAffiliateInvoice(f.env,invoice)).state,"commission_reversed");assert.equal((await affiliateBalance(f.db,AFF)).pending_cents,"0");assert.throws(()=>f.db.raw.exec("DELETE FROM ravenos_affiliate_commission_ledger"),/append_only/);});
test("a refund after manual payout records a recoverable adjustment",async()=>{const f=await referredFixture();const invoice=paidInvoice(f);await reconcileAffiliateInvoice(f.env,invoice);for(const action of ["approve","paid"])await recordAffiliateManualAction(f.db,{invoice_id:invoice,action,amount_cents:"3725",reference:`proof_${action}_123`,operator_user_id:"usr_operator",now:NOW+50*86400});paidInvoice(f,{cash:0,ref:"evt_refund123"});await reconcileAffiliateInvoice(f.env,invoice);const balance=await affiliateBalance(f.db,AFF);assert.equal(balance.available_cents,"0");assert.equal(balance.recoverable_cents,"3725");});
test("same Raven account cannot refer itself",async()=>{const f=await referredFixture();assert.throws(()=>f.db.raw.prepare("INSERT INTO ravenos_referral_attributions (attribution_id,referred_user_id,referrer_user_id,referral_code_snapshot,attribution_method,attribution_digest,attributed_at) VALUES (?,?,?,?,'authenticated_claim',?,?)").run("rat_"+"b".repeat(20),AFF,AFF,f.dashboard.referral_code,"b".repeat(64),NOW),/CHECK/);});
test("affiliate dashboard contains aggregate revenue only and disclosure is easy to copy",async()=>{const f=await referredFixture();await reconcileAffiliateInvoice(f.env,paidInvoice(f,{cash:10000}));const dashboard=await affiliateDashboard(f.env,AFF);assert.equal(dashboard.metrics.accounts_created,1);assert.match(dashboard.disclosure,/I earn a commission if you subscribe/);const serialized=JSON.stringify(dashboard);for(const secret of [f.account.user_id,f.identity.email,"wallet_address","cashback_balance","trading_volume"])assert.ok(!serialized.includes(secret));assert.equal(dashboard.events[0].qualifying_revenue_cents,"10000");});
