import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { routeCustomerShielded, CUSTOMER_SHIELDED_ROUTE as BASE, createShieldedQuoteCache } from "../lib/customer_shielded_routes.mjs";
import { SHIELDED_FLAGS, SHIELDED_BOUNDARY } from "../lib/customer_trade/shielded_reserve.mjs";
import { SHIELDED_ASSETS } from "../lib/customer_trade/shielded_route_providers.mjs";
import { planShieldedCapital } from "../lib/customer_trade/shielded_capital_planner.mjs";
const now = Date.now();
const env = Object.fromEntries(SHIELDED_FLAGS.map(k => [k,"1"]));
const input = { action: "SHIELDED_DEPLOY", network: "solana_usdc", amount_usd: "500" };
function request(body, { origin = "https://app.ravenos.xyz", path = body ? `${BASE}/quote` : BASE, method = body ? "POST" : "GET" } = {}) { return new Request(origin+path, { method, headers: { origin, "content-type":"application/json", "x-ravenos-csrf":"test" }, ...(method === "POST" ? {body:JSON.stringify(body)} : {}) }); }
function fixture(extra = {}) {
  const calls = { quotes: [], tokens:0, auth:[], limited:0 };
  const catalog = Object.values(SHIELDED_ASSETS).map(a=>({assetId:a.id,blockchain:a.chain,decimals:a.decimals,symbol:a.symbol,contractAddress:a.contract,price:a.symbol==='ZEC'?'100':'1',priceUpdatedAt:new Date(now).toISOString()}));
  const deps = { nowMs:now, cache:createShieldedQuoteCache(), authorizeRequest:async (r,e,d,policy)=>{calls.auth.push(policy);return {principal:{user_id:'test-pro'},now:Math.floor(now/1000),response_headers:new Headers(),store:{}};}, readAccess:async()=>({pro:true}), rateLimit:async()=>{calls.limited++;return {allowed:true};}, provider:{ id:'near_1click',tokens:async()=>{calls.tokens++;return catalog;},quote:async i=>{calls.quotes.push(i);return {available:true,boundary:SHIELDED_BOUNDARY,research_expires_at:new Date(now+30000).toISOString()};}}, ...extra };
  return {calls,deps};
}
test('anonymous, Standard and wrong-origin requests cannot reach the provider', async()=>{
  for(const denied of [{authorizeRequest:async()=>({response:Response.json({error:'authentication_required'},{status:401})})},{readAccess:async()=>({pro:false})}]) {const {deps,calls}=fixture(denied);const r=await routeCustomerShielded(request(input),env,deps);assert([401,403].includes(r.status));assert.equal(calls.tokens,0);}
  const {deps,calls}=fixture();assert.equal((await routeCustomerShielded(request(input,{origin:'https://ravenos.xyz'}),env,deps)).status,404);assert.equal(calls.auth.length,0);
});
test('preview uses existing session and CSRF authorization; no wallet or payment needed',async()=>{const {deps,calls}=fixture();assert.equal((await routeCustomerShielded(request(input),env,deps)).status,200);assert.equal(calls.auth[0].require_csrf,true);assert.equal(calls.quotes[0].boundary.signing_enabled,false);assert.equal('destination_wallet' in calls.quotes[0],false);});
test('trial and paid Pro share the same access gate',async()=>{for(const source of ['paid','trial']) {const {deps}=fixture({readAccess:async()=>({pro:true,source})});assert.equal((await routeCustomerShielded(request(input),env,deps)).status,200);}});
test('capabilities expose no invented reserve balance or viewing keys',async()=>{const {deps}=fixture();const r=await routeCustomerShielded(request(),env,deps);const b=await r.json();assert.equal(b.reserve.balance_zatoshis,null);assert.equal(b.reserve.verified,false);assert.equal(b.zec_price.usd_micros,'100000000');assert.equal(b.boundary.live_execution_enabled,false);assert.match(r.headers.get('cache-control'),/no-store/);assert.equal(b.unsupported[0].key,'robinhood_usdc');});
test('all master flags and per-action switches fail closed before provider I/O',async()=>{for(const key of [...SHIELDED_FLAGS.slice(0,3),'SHIELDED_DEPLOY_ENABLED']){const {deps,calls}=fixture();assert([400,503].includes((await routeCustomerShielded(request(input),{...env,[key]:'0'},deps)).status));assert.equal(calls.tokens,0);}});
test('live flag never creates an executable path',async()=>{const {deps}=fixture();const r=await routeCustomerShielded(request(input),{...env,LIVE_SHIELDED_EXECUTION_ENABLED:'1'},deps);assert.equal((await r.json()).quote.boundary.live_execution_enabled,false);assert.equal((await routeCustomerShielded(request(input,{path:`${BASE}/send`}),env,deps)).status,404);});
test('strict input rejects destinations, keys, arbitrary providers, huge values and proto keys',async()=>{for(const patch of [{destination:'0x123'},{viewing_key:'uview1private'},{private_key:'bad'},{provider:'https://bad.invalid'},{network:'toString'},{network:'robinhood_usdc'},{amount_usd:'50000.01'},{amount_usd:100},{amount_usd:'1e5'},{action:'STANDARD_COMPARE'},{amount_usd:'0.99'}]){const {deps,calls}=fixture();const r=await routeCustomerShielded(request({...input,...patch}),env,deps);assert.equal(r.status,400,JSON.stringify(patch));assert.equal(calls.tokens,0);}});
test('rate limit blocks even cached requests and does not leak provider errors',async()=>{const {deps,calls}=fixture({rateLimit:async()=>({allowed:false})});assert.equal((await routeCustomerShielded(request(input),env,deps)).status,429);assert.equal(calls.tokens,0);const f=fixture({provider:{tokens:async()=>{throw Error('private secret detail');}}});const r=await routeCustomerShielded(request(),env,f.deps);assert.equal(r.status,503);assert.doesNotMatch(await r.text(),/private secret detail/);});
test('concurrent equal previews share a request; action and expiry separate results',async()=>{const {deps,calls}=fixture();await Promise.all([routeCustomerShielded(request(input),env,deps),routeCustomerShielded(request(input),env,deps)]);assert.equal(calls.tokens,1);assert.equal(calls.quotes.length,1);assert.equal(calls.limited,2);await routeCustomerShielded(request({...input,action:'SHIELDED_RETURN'}),env,deps);assert.equal(calls.quotes.length,2);assert.equal(calls.quotes[1].source,'solana_usdc');await routeCustomerShielded(request(input),env,{...deps,nowMs:now+26000});assert.equal(calls.quotes.length,3);});
test('Send requests fixed output and stale prices are omitted',async()=>{const {deps,calls}=fixture();await routeCustomerShielded(request({...input,action:'SHIELDED_SEND'}),env,deps);assert.equal(calls.quotes[0].amount_mode,'EXACT_OUTPUT');assert.equal(calls.quotes[0].amount_atomic,'500000000');const r=await routeCustomerShielded(request(),env,{...deps,nowMs:now+700000});assert.equal((await r.json()).zec_price,null);});
test('unavailable quotes are not cached as successes',async()=>{const {deps,calls}=fixture();deps.provider.quote=async()=>{calls.quotes.push(1);return {available:false};};await routeCustomerShielded(request(input),env,deps);await routeCustomerShielded(request(input),env,deps);assert.equal(calls.quotes.length,2);});
test('local planner uses precise ZEC value and cannot turn reserve into Copy buying power',()=>{const r=planShieldedCapital({reserve_zec:'76',working_usdc:'2400',target_usdc:'5000',zec_price_usd_micros:'100000000',price_move_percent:-30});assert.equal(r.reserve_usd_micros,'7600000000');assert.equal(r.reserve_after_move_usd_micros,'5320000000');assert.equal(r.shortfall_usdc_micros,'2600000000');assert.equal(r.copy_ready,false);assert.equal(r.shielded_immediately_executable,false);});
test('excess stays a local scenario; tiny values round down and invalid amounts fail',()=>{const r=planShieldedCapital({reserve_zec:'0.00000001',working_usdc:'13200',target_usdc:'10000',zec_price_usd_micros:'123456789'});assert.equal(r.excess_usdc_micros,'3200000000');assert.equal(r.reserve_usd_micros,'1');assert.equal(r.live_funding_authorized,false);assert.throws(()=>planShieldedCapital({reserve_zec:'-1',working_usdc:'0',target_usdc:'0',zec_price_usd_micros:'1'}));});
test('customer bundle has no signing, analytics or scenario storage path',()=>{const source=readFileSync(new URL('../client/ravenos-reserve-entry.js',import.meta.url),'utf8');assert.doesNotMatch(source,/localStorage|sessionStorage|sendBeacon|signTransaction|sendTransaction|privateKey|viewingKey/);assert.match(source,/planShieldedCapital/);const config=JSON.parse(readFileSync(new URL('../config/customer_security.json',import.meta.url)));assert.equal(config.shielded_reserve_research.LIVE_SHIELDED_EXECUTION_ENABLED,false);});
test('oversized streaming and malformed JSON requests stop before provider work',async()=>{
 const {deps,calls}=fixture();let cancelled=false;
 const body=new ReadableStream({pull(c){c.enqueue(new Uint8Array(1100));},cancel(){cancelled=true;}});
 const req=new Request('https://app.ravenos.xyz'+BASE+'/quote',{method:'POST',body,duplex:'half',headers:{'content-type':'application/json'}});
 assert.equal((await routeCustomerShielded(req,env,deps)).status,413);assert.equal(cancelled,true);assert.equal(calls.tokens,0);
 const malformed=new Request('https://app.ravenos.xyz'+BASE+'/quote',{method:'POST',body:'{',headers:{'content-type':'application/json'}});
 assert.equal((await routeCustomerShielded(malformed,env,deps)).status,400);
});
