import assert from "node:assert/strict";
import fs from "node:fs";

const featureScript = fs.readFileSync("ravenos-features.js", "utf8");
const explanationScript = fs.readFileSync("ravenos-explanations.js", "utf8");
const replayScript = fs.readFileSync("ravenos-replay.js", "utf8");
const participantScript = fs.readFileSync("ravenos-participants.js", "utf8");
const accessScript = fs.readFileSync("ravenos-access.js", "utf8");
const liveScript = fs.readFileSync("ravenos-live.js", "utf8");
const publicManifest = fs.readFileSync("public-data/ravenos_public_manifest.json", "utf8");
const publicMethodology = fs.readFileSync("docs/ravenos_public_methodology.md", "utf8");
const publicOriginBridge = fs.readFileSync("docs/ravenos_public_origin_bridge.md", "utf8");
const docsReadme = fs.readFileSync("docs/README.md", "utf8");
const conversionAudit = fs.readFileSync("data/runtime/ravenos_conversion_monetization_audit.md", "utf8");
const conversionPlan = fs.readFileSync("data/runtime/ravenos_conversion_monetization_plan.json", "utf8");
const terminal = fs.readFileSync("terminal/index.html", "utf8");
const research = fs.readFileSync("research/index.html", "utf8");
const atlas = fs.readFileSync("atlas/index.html", "utf8");
const watchlists = fs.readFileSync("watchlists/index.html", "utf8");
const perps = fs.readFileSync("perps/index.html", "utf8");
const opportunity = fs.readFileSync("opportunity/index.html", "utf8");
const brief = fs.readFileSync("brief/index.html", "utf8");
const replayPage = fs.readFileSync("replay/index.html", "utf8");
const outcomes = fs.readFileSync("outcomes/index.html", "utf8");
const memory = fs.readFileSync("memory/index.html", "utf8");
const behavior = fs.readFileSync("behavior/index.html", "utf8");
const solanaChain = fs.readFileSync("chains/solana/index.html", "utf8");
const baseChain = fs.readFileSync("chains/base/index.html", "utf8");
const ethereumChain = fs.readFileSync("chains/ethereum/index.html", "utf8");
const faq = fs.readFileSync("faq/index.html", "utf8");
const disclosures = fs.readFileSync("disclosures/index.html", "utf8");

const githubDocsHref = "https://github.com/walletbehavior/ravenos-public/tree/main/docs";
const coreResearchPages = [
  ["terminal", terminal],
  ["opportunity", opportunity],
  ["brief", brief],
  ["replay", replayPage],
  ["outcomes", outcomes],
  ["memory", memory],
  ["behavior", behavior],
  ["research", research],
  ["solana chain", solanaChain],
  ["base chain", baseChain],
  ["ethereum chain", ethereumChain],
];

for (const [name, page] of coreResearchPages) {
  assert.match(page, /\/terminal\//, `${name} should link to Terminal`);
  assert.match(page, /\/brief\//, `${name} should link to Brief`);
  assert.match(page, /\/opportunity\//, `${name} should link to Opportunity`);
  assert.match(page, /\/replay\//, `${name} should link to Replay`);
  assert.match(page, /\/outcomes\//, `${name} should link to Outcomes`);
  assert.match(page, /\/memory\//, `${name} should link to Memory`);
  assert.match(page, /\/behavior\//, `${name} should link to Behavior`);
  assert.match(page, /\/research\//, `${name} should link to Research`);
  assert.ok(page.includes(githubDocsHref), `${name} should link to public docs`);
}

assert.match(featureScript, /function FeatureGate/);
assert.match(featureScript, /function lockedPreview/);
assert.match(featureScript, /AccessBadge/);
assert.match(featureScript, /CoverageBadge/);
assert.match(featureScript, /data-feature/);
assert.match(explanationScript, /ExplanationPanel/);
assert.match(explanationScript, /ScoreBreakdown/);
assert.match(explanationScript, /ConfidenceBadge/);
assert.match(explanationScript, /ConfidencePanel/);
assert.match(explanationScript, /EvidenceCard/);
assert.match(explanationScript, /ProvenanceStrip/);
assert.match(explanationScript, /ScoreTransparency/);
assert.match(explanationScript, /WhyItMatters/);
assert.match(explanationScript, /EvidenceList/);
assert.match(explanationScript, /WhyThisChanged/);
assert.match(explanationScript, /Historical analogs/);
assert.match(explanationScript, /Top Positive Contributors/);
assert.match(explanationScript, /Top Negative Contributors/);
assert.match(replayScript, /ReplayOutcomePanel/);
assert.match(replayScript, /similarStructures/);
assert.match(replayScript, /Outcome distribution/);
assert.match(participantScript, /ParticipantPanel/);
assert.match(participantScript, /contribution/);
assert.match(participantScript, /Distribution risk/);

assert.match(accessScript, /API unavailable\. Subscription and future token access checks are temporarily unavailable\./);
assert.match(accessScript, /entitlements/);
assert.match(liveScript, /DEFAULT_INTERVALS/);
assert.match(liveScript, /document\.hidden/);
assert.match(liveScript, /data-ravenos-live-strip/);
assert.match(liveScript, /renderOpportunityLive/);
assert.match(liveScript, /renderOpportunityTables/);
assert.match(liveScript, /renderOpportunityTiles/);
assert.match(liveScript, /renderOpportunityMatrix/);
assert.match(liveScript, /renderOpportunityDrilldown/);
assert.match(liveScript, /renderBriefLive/);
assert.match(liveScript, /renderReplayLive/);
assert.match(liveScript, /renderOutcomesLive/);
assert.match(liveScript, /renderMemoryLive/);
assert.match(liveScript, /renderBehaviorLive/);
assert.match(liveScript, /renderTerminalLive/);
assert.match(liveScript, /renderChainLive/);
assert.match(liveScript, /marketVenueLabel/);
assert.match(liveScript, /escapeHtml/);
assert.match(publicManifest, /"normal_pages_rebuild_required_for_data": false/);
assert.match(publicManifest, /RAVENOS_PUBLIC_ORIGIN_URL/);
assert.ok(publicManifest.includes('"public_endpoint": "/api/opportunity"'));
assert.match(publicMethodology, /RavenOS Public Methodology/);
assert.match(publicMethodology, /What is happening\?/);
assert.match(publicMethodology, /Top positive contributors/);
assert.match(publicMethodology, /does not publish proprietary weights/i);
assert.match(publicMethodology, /User-facing coverage labels/);
assert.doesNotMatch(publicMethodology, /WalletMemory|ShadowMirror|canary|Turnkey|signer|treasury/i);
assert.match(publicOriginBridge, /RavenOS Public Origin Bridge/);
assert.match(publicOriginBridge, /Fixed allowlisted paths only/);
assert.match(publicOriginBridge, /127\.0\.0\.1:8788/);
assert.match(publicOriginBridge, /last-known-good fallback/);
assert.match(docsReadme, /RavenOS Public Documentation/);
assert.match(docsReadme, /Public Methodology/);
assert.match(docsReadme, /FAQ/);
assert.match(docsReadme, /Disclosures/);
assert.doesNotMatch(docsReadme, /WalletMemory|ShadowMirror|canary|Turnkey|signer|treasury/i);
assert.match(conversionAudit, /Visitor to user to Pro to Desk|visitor to user to Pro to Desk/i);
assert.match(conversionAudit, /Free should prove the product quickly/);
assert.match(conversionAudit, /Do not imply Raven guarantees outcomes/);
assert.match(conversionPlan, /"full_replay_lab"/);
assert.match(conversionPlan, /"scores_without_visible_evidence"/);

assert.match(terminal, /data-feature="free_token_lookup"/);
assert.match(terminal, /data-feature="basic_chart"/);
assert.match(terminal, /data-feature="full_heatmaps"/);
assert.match(terminal, /ravenos-features\.js/);
assert.match(terminal, /ravenos-explanations\.js/);
assert.match(terminal, /ravenos-replay\.js/);
assert.match(terminal, /ravenos-participants\.js/);
assert.match(terminal, /data-feature="participant_intelligence"/);
assert.match(terminal, /github\.com\/walletbehavior\/ravenos-public\/tree\/main\/docs/);
assert.match(terminal, /\/faq\//);
assert.match(terminal, /\/disclosures\//);
assert.match(terminal, /\/opportunity\//);
assert.match(terminal, /\/brief\//);
assert.match(terminal, /\/replay\//);
assert.match(terminal, /data-ravenos-api="\/api\/terminal"/);
assert.match(terminal, /ravenos-live\.js/);
assert.match(terminal, /Hot Sector/);
assert.match(terminal, /id="dexSearchInput"/);
assert.match(terminal, /Search symbol, token, pair, or contract/);
assert.doesNotMatch(terminal, /dexSearchInputPanel/);
assert.match(terminal, /id="tickerPressure"/);
assert.match(terminal, /id="tickerCoverage"/);
assert.match(terminal, /id="contextCoverage"/);
assert.match(terminal, /overlayContext/);
assert.match(terminal, /raven-chart-timeframes\.js/);
assert.match(terminal, /function selectedTimeframe/);
assert.match(terminal, /selectedChartState/);
assert.match(terminal, /id="chartDebug"/);
assert.match(terminal, /id="timeframeWindow"/);
assert.match(terminal, /timeframeMetrics/);
assert.match(terminal, /RavenChartTimeframes\?\.makeTimeframeCandles/);
assert.match(terminal, /chartHost\.dataset\.chartKey = state\.key/);
assert.match(terminal, /\["micro_caps", "Micro Caps", "active"\]/);
assert.match(terminal, /\["perps_majors", "Majors", "active"\]/);
assert.match(terminal, /function isCryptoCategory/);
assert.match(terminal, /function perpsClass/);
assert.match(terminal, /function hydrateCategoryOptions/);
assert.match(terminal, /\/api\/dexscreener\/trending\?category=/);
assert.match(terminal, /else if \(options\[0\]\) select\.value = options\[0\]\.asset/);
assert.match(terminal, /id="capOutcomeHeatmap"/);
assert.match(terminal, /function renderCapOutcomeHeatmap/);
assert.match(terminal, /function outcomeScore/);
assert.match(terminal, /function renderCapDrilldown/);
assert.match(terminal, /function capDrilldownModel/);
assert.match(terminal, /function rotationGroups/);
assert.match(terminal, /data-rotation-type/);
assert.match(terminal, /Why This Cell Reads This Way/);
assert.match(terminal, /EQUITY_CATALOG/);
assert.match(terminal, /FREE_MARKET_SYMBOLS/);
assert.match(terminal, /CORE_STOCK_SYMBOLS/);
assert.match(terminal, /CORE_ETF_SYMBOLS/);
assert.match(terminal, /function equityLookupRows/);
assert.match(terminal, /function shouldPreferMarketLookup/);
assert.match(terminal, /function broaderMarketPreviewRow/);
assert.match(terminal, /function knownCryptoLikeSymbol/);
assert.match(terminal, /data-market-index/);
assert.match(terminal, /Expanded preview/);
assert.doesNotMatch(terminal, /Pro coverage/);
assert.doesNotMatch(terminal, /id="providerSource"/);
assert.doesNotMatch(terminal, /id="staleTimestamp"/);
assert.doesNotMatch(terminal, /id="tokenAccessStatus"/);
assert.doesNotMatch(terminal, /"Hyperliquid", "large cap"/);
assert.match(terminal, /Hyperliquid perps/);
assert.match(terminal, /Market\/Venue/);

assert.match(research, /data-feature="full_research"/);
assert.match(research, /data-ravenos-api="\/api\/research"/);
assert.match(research, /\/api\/research/);
assert.match(research, /Research rows in live public read/);
assert.match(research, /researchSource/);
assert.match(research, /hydrateLiveResearch/);
assert.match(research, /failure_analysis/);
assert.match(research, /candidate_lanes/);
assert.match(research, /ravenos-features\.js/);
assert.match(research, /ravenos-explanations\.js/);
assert.match(research, /ravenos-replay\.js/);
assert.match(research, /ravenos-participants\.js/);
assert.match(research, /Key Findings This Week/);
assert.match(research, /What Worked/);
assert.match(research, /Outcome Quality/);
assert.match(research, /Replay Strength/);
assert.match(research, /Developer Mode/);
assert.match(research, /Why Raven Believes This/);
assert.match(research, /Why It Matters/);
assert.match(research, /\/brief\//);
assert.match(research, /\/replay\//);
assert.match(research, /\/outcomes\//);
assert.match(research, /\/memory\//);
assert.match(research, /\/behavior\//);

assert.match(atlas, /data-feature="atlas_context"/);
assert.match(atlas, /data-coverage-badge/);
assert.match(atlas, /market regime/);
assert.match(atlas, /Liquidity conditions/);
assert.match(atlas, /Breadth quality/);
assert.match(atlas, /Volatility environment/);
assert.match(atlas, /Cross-market posture/);
assert.doesNotMatch(atlas, /Tradier is temporarily unavailable/);
assert.doesNotMatch(atlas, /Provider status and fallback quality/);

assert.match(watchlists, /data-feature="watchlists"/);
assert.match(watchlists, /\/api\/watchlists/);
assert.match(watchlists, /Free users can keep one compact watchlist/);
assert.match(watchlists, /ravenos-explanations\.js/);
assert.match(watchlists, /ravenos-replay\.js/);

assert.match(perps, /data-feature="perps_intelligence"/);
assert.match(perps, /\/api\/hyperliquid\/perps/);
assert.match(perps, /RavenOS Perps Intelligence/);
assert.match(perps, /ravenos-participants\.js/);
assert.match(perps, /ravenos-replay\.js/);

assert.match(opportunity, /RavenOS Opportunity Board/);
assert.match(opportunity, /data-ravenos-api="\/api\/opportunity"/);
assert.match(opportunity, /ravenos-live\.js/);
assert.match(opportunity, /id="oppHotSector"/);
assert.match(opportunity, /id="oppHeroSurface"/);
assert.match(opportunity, /id="oppUsableSample"/);
assert.match(opportunity, /id="oppTopTiles"/);
assert.match(opportunity, /id="oppChainRows"/);
assert.match(opportunity, /id="oppCapRows"/);
assert.match(opportunity, /id="oppMatrix"/);
assert.match(opportunity, /id="oppDrilldown"/);
assert.match(opportunity, /Hot Sector/);
assert.match(opportunity, /Solana Micro/);
assert.match(opportunity, /Opportunity evidence and provenance/);
assert.match(opportunity, /Confidence Provenance/);
assert.match(opportunity, /Validation Context/);
assert.match(opportunity, /Top Opportunity Tiles/);
assert.match(opportunity, /Rotation \/ What Changed/);
assert.match(opportunity, /Raven Intelligence Stack/);
assert.match(opportunity, /Participation Memory/);
assert.match(opportunity, /Replay Intelligence/);
assert.match(opportunity, /Validation Layer/);
assert.doesNotMatch(opportunity, /WalletMemory/);
assert.doesNotMatch(opportunity, /ShadowMirror/);
assert.match(opportunity, /Chain Opportunity Snapshot/);
assert.match(opportunity, /Cap Band Snapshot/);
assert.match(opportunity, /Chain x Cap Band Matrix/);
assert.match(opportunity, /Open Solana Micro Drilldown/);
assert.match(opportunity, /What&apos;s Working/);
assert.match(opportunity, /What Would Change The Read/);

assert.match(brief, /RavenOS Daily Brief/);
assert.match(brief, /data-ravenos-api="\/api\/brief"/);
assert.match(brief, /ravenos-live\.js/);
assert.match(brief, /id="briefReadTitle"/);
assert.match(brief, /id="briefHeroSurface"/);
assert.match(brief, /id="briefBestSurface"/);
assert.match(brief, /id="briefUpdated"/);
assert.match(brief, /id="briefCoverage"/);
assert.match(brief, /id="briefAnalogCount"/);
assert.match(brief, /Current Market Read/);
assert.match(brief, /Best opportunity surface/);
assert.match(brief, /Most similar regime/);
assert.match(brief, /Why It Matters/);
assert.match(brief, /Historical analogs/);
assert.match(brief, /Daily Change Table/);
assert.match(brief, /\/outcomes\//);
assert.match(brief, /\/memory\//);

assert.match(replayPage, /RavenOS Replay Lab/);
assert.match(replayPage, /data-ravenos-api="\/api\/replay"/);
assert.match(replayPage, /id="replayAnalogCount"/);
assert.match(replayPage, /id="replayAnalogRows"/);
assert.match(replayPage, /id="replayExpanded"/);
assert.match(replayPage, /id="replayCoverage"/);
assert.match(replayPage, /Have we seen this before/);
assert.match(replayPage, /12 Similar Structures/);
assert.match(replayPage, /Why Similar/);
assert.match(replayPage, /Outcome Distribution/);
assert.match(replayPage, /Historical similarity does not guarantee future outcomes/);
assert.match(replayPage, /\/outcomes\//);
assert.match(replayPage, /\/memory\//);
assert.match(replayPage, /\/behavior\//);

assert.match(outcomes, /RavenOS Outcome Dashboard/);
assert.match(outcomes, /data-ravenos-api="\/api\/outcomes"/);
assert.match(outcomes, /id="outBreakdownRows"/);
assert.match(outcomes, /id="outHeroBadge"/);
assert.match(outcomes, /id="outRewardingCount"/);
assert.match(outcomes, /Public Outcome Scorecard/);
assert.match(outcomes, /Rewarding/);
assert.match(outcomes, /Punishing/);
assert.match(outcomes, /Insufficient Sample/);
assert.match(outcomes, /Evidence/);
assert.match(outcomes, /descriptive research/i);
assert.doesNotMatch(outcomes, /WalletMemory|ShadowMirror|0x[a-fA-F0-9]{40}|[1-9A-HJ-NP-Za-km-z]{32,44}/);

assert.match(memory, /RavenOS Market Memory/);
assert.match(memory, /data-ravenos-api="\/api\/memory"/);
assert.match(memory, /id="memoryReadTitle"/);
assert.match(memory, /id="memoryDominant"/);
assert.match(memory, /id="memoryCommonRows"/);
assert.match(memory, /id="memoryFreshness"/);
assert.match(memory, /Current Structure Rank/);
assert.match(memory, /Most Common Structures/);
assert.match(memory, /Regime Transitions/);
assert.match(memory, /Similarity History/);
assert.match(memory, /Public Methodology/);
assert.doesNotMatch(memory, /WalletMemory|ShadowMirror|0x[a-fA-F0-9]{40}/);

assert.match(behavior, /RavenOS Behavior Explorer/);
assert.match(behavior, /data-ravenos-api="\/api\/behavior"/);
assert.match(behavior, /id="behaviorReadTitle"/);
assert.match(behavior, /id="behaviorRows"/);
assert.match(behavior, /id="behaviorState"/);
assert.match(behavior, /id="behaviorUpdated"/);
assert.match(behavior, /Participation is returning, but still concentrated/);
assert.match(behavior, /What Raven believes/);
assert.doesNotMatch(behavior, /Fragile \/ Observable/);
assert.doesNotMatch(behavior, /Mixed by chain/);
assert.doesNotMatch(behavior, /6h context/);
assert.match(behavior, /Market \/ Venue/);
assert.match(behavior, /Participation mix|Aggregate Participant Context/);
assert.match(behavior, /Breadth & Concentration/);
assert.match(behavior, /Survival \/ Followthrough/);
assert.match(behavior, /Public Methodology/);
assert.match(behavior, /Privacy Boundary/);
assert.doesNotMatch(behavior, /WalletMemory|ShadowMirror|canary|live execution|0x[a-fA-F0-9]{40}/i);

assert.match(solanaChain, /RavenOS Solana Intelligence/);
assert.match(solanaChain, /data-ravenos-api="\/api\/chains\/solana"/);
assert.match(solanaChain, /id="chainTopSurface"/);
assert.match(solanaChain, /id="chainSample"/);
assert.match(solanaChain, /id="chainCurrentRead"/);
assert.match(solanaChain, /id="chainWeakestArea"/);
assert.match(solanaChain, /id="chainTopAssets"/);
assert.match(solanaChain, /id="chainCapRows"/);
assert.match(solanaChain, /Micro-cap participation is broadening/);
assert.match(solanaChain, /Top opportunity surface/);
assert.match(solanaChain, /Cap Band Drilldown/);
assert.match(solanaChain, /Historical Context/);
assert.match(baseChain, /RavenOS Base Intelligence/);
assert.match(baseChain, /data-ravenos-api="\/api\/chains\/base"/);
assert.match(baseChain, /id="chainCapRows"/);
assert.match(baseChain, /Cap Band Drilldown/);
assert.match(baseChain, /Small-cap rotation is building/);
assert.match(baseChain, /Coverage/);
assert.match(ethereumChain, /RavenOS Ethereum Intelligence/);
assert.match(ethereumChain, /data-ravenos-api="\/api\/chains\/ethereum"/);
assert.match(ethereumChain, /id="chainCapRows"/);
assert.match(ethereumChain, /Cap Band Drilldown/);
assert.match(ethereumChain, /Liquidity is stable, but breadth is narrow/);
assert.match(ethereumChain, /Why It Matters/);

assert.match(faq, /What is RavenOS\?/);
assert.match(faq, /Does RavenOS provide trade signals\?/);
assert.match(faq, /Flow Score is not a trade signal/);
assert.match(faq, /The goal is not prediction\. The goal is understanding\./);

assert.match(disclosures, /Last Updated: June 2026/);
assert.match(disclosures, /Not Investment Advice/);
assert.match(disclosures, /No Brokerage or Trade Execution/);
assert.match(disclosures, /Token-based access should be understood solely as a software access mechanism/);
