import assert from "node:assert/strict";
import fs from "node:fs";

const featureScript = fs.readFileSync("ravenos-features.js", "utf8");
const explanationScript = fs.readFileSync("ravenos-explanations.js", "utf8");
const replayScript = fs.readFileSync("ravenos-replay.js", "utf8");
const participantScript = fs.readFileSync("ravenos-participants.js", "utf8");
const accessScript = fs.readFileSync("ravenos-access.js", "utf8");
const terminal = fs.readFileSync("terminal/index.html", "utf8");
const research = fs.readFileSync("research/index.html", "utf8");
const atlas = fs.readFileSync("atlas/index.html", "utf8");
const watchlists = fs.readFileSync("watchlists/index.html", "utf8");
const perps = fs.readFileSync("perps/index.html", "utf8");
const faq = fs.readFileSync("faq/index.html", "utf8");
const disclosures = fs.readFileSync("disclosures/index.html", "utf8");

assert.match(featureScript, /function FeatureGate/);
assert.match(featureScript, /function lockedPreview/);
assert.match(featureScript, /AccessBadge/);
assert.match(featureScript, /CoverageBadge/);
assert.match(featureScript, /data-feature/);
assert.match(explanationScript, /ExplanationPanel/);
assert.match(explanationScript, /ScoreBreakdown/);
assert.match(explanationScript, /ConfidenceBadge/);
assert.match(explanationScript, /EvidenceList/);
assert.match(explanationScript, /WhyThisChanged/);
assert.match(replayScript, /ReplayOutcomePanel/);
assert.match(replayScript, /similarStructures/);
assert.match(replayScript, /Outcome distribution/);
assert.match(participantScript, /ParticipantPanel/);
assert.match(participantScript, /contribution/);
assert.match(participantScript, /Distribution risk/);

assert.match(accessScript, /API unavailable\. Subscription and future token access checks are temporarily unavailable\./);
assert.match(accessScript, /entitlements/);

assert.match(terminal, /data-feature="free_token_lookup"/);
assert.match(terminal, /data-feature="basic_chart"/);
assert.match(terminal, /data-feature="full_heatmaps"/);
assert.match(terminal, /ravenos-features\.js/);
assert.match(terminal, /ravenos-explanations\.js/);
assert.match(terminal, /ravenos-replay\.js/);
assert.match(terminal, /ravenos-participants\.js/);
assert.match(terminal, /data-feature="participant_intelligence"/);
assert.match(terminal, /github\.com\/walletbehavior\/ravenos-public\/tree\/main\/docs/);
assert.match(terminal, /\/faq\//);
assert.match(terminal, /\/disclosures\//);
assert.match(terminal, /id="dexSearchInput"/);
assert.match(terminal, /Search symbol, token, pair, or contract/);
assert.doesNotMatch(terminal, /dexSearchInputPanel/);
assert.match(terminal, /id="tickerPressure"/);
assert.match(terminal, /id="tickerCoverage"/);
assert.match(terminal, /id="contextCoverage"/);
assert.match(terminal, /overlayContext/);
assert.match(terminal, /raven-chart-timeframes\.js/);
assert.match(terminal, /function selectedTimeframe/);
assert.match(terminal, /selectedChartState/);
assert.match(terminal, /id="chartDebug"/);
assert.match(terminal, /id="timeframeWindow"/);
assert.match(terminal, /timeframeMetrics/);
assert.match(terminal, /RavenChartTimeframes\?\.makeTimeframeCandles/);
assert.match(terminal, /chartHost\.dataset\.chartKey = state\.key/);
assert.match(terminal, /\["micro_caps", "Micro Caps", "active"\]/);
assert.match(terminal, /\["opportunity_board", "Opportunity Board", "active"\]/);
assert.match(terminal, /\["perps_majors", "Majors", "active"\]/);
assert.match(terminal, /function isCryptoCategory/);
assert.match(terminal, /function perpsClass/);
assert.match(terminal, /function hydrateCategoryOptions/);
assert.match(terminal, /\/api\/dexscreener\/trending\?category=/);
assert.match(terminal, /else if \(options\[0\]\) select\.value = options\[0\]\.asset/);
assert.match(terminal, /id="capOutcomeHeatmap"/);
assert.match(terminal, /Opportunity Board/);
assert.match(terminal, /function renderCapOutcomeHeatmap/);
assert.match(terminal, /function outcomeScore/);
assert.match(terminal, /function renderCapDrilldown/);
assert.match(terminal, /function capDrilldownModel/);
assert.match(terminal, /Chain Opportunity Snapshot/);
assert.match(terminal, /Cap Band Snapshot/);
assert.match(terminal, /function renderRotationSnapshot/);
assert.match(terminal, /function rotationGroups/);
assert.match(terminal, /data-rotation-type/);
assert.match(terminal, /data-heatmap-asset/);
assert.match(terminal, /data-heatmap-key/);
assert.match(terminal, /data-drill-asset/);
assert.match(terminal, /Why This Cell Reads This Way/);
assert.match(terminal, /EQUITY_CATALOG/);
assert.match(terminal, /FREE_MARKET_SYMBOLS/);
assert.match(terminal, /CORE_STOCK_SYMBOLS/);
assert.match(terminal, /CORE_ETF_SYMBOLS/);
assert.match(terminal, /function equityLookupRows/);
assert.match(terminal, /function shouldPreferMarketLookup/);
assert.match(terminal, /function broaderMarketPreviewRow/);
assert.match(terminal, /function knownCryptoLikeSymbol/);
assert.match(terminal, /data-market-index/);
assert.match(terminal, /Expanded preview/);
assert.doesNotMatch(terminal, /Pro coverage/);
assert.doesNotMatch(terminal, /id="providerSource"/);
assert.doesNotMatch(terminal, /id="staleTimestamp"/);
assert.doesNotMatch(terminal, /id="tokenAccessStatus"/);

assert.match(research, /data-feature="full_research"/);
assert.match(research, /failure_analysis/);
assert.match(research, /candidate_lanes/);
assert.match(research, /ravenos-features\.js/);
assert.match(research, /ravenos-explanations\.js/);
assert.match(research, /ravenos-replay\.js/);
assert.match(research, /ravenos-participants\.js/);
assert.match(research, /Key Findings This Week/);
assert.match(research, /What Worked/);
assert.match(research, /Outcome Quality/);
assert.match(research, /Replay Strength/);
assert.match(research, /Developer Mode/);

assert.match(atlas, /data-feature="atlas_context"/);
assert.match(atlas, /data-coverage-badge/);
assert.match(atlas, /market regime/);
assert.match(atlas, /Liquidity conditions/);
assert.match(atlas, /Breadth quality/);
assert.match(atlas, /Volatility environment/);
assert.match(atlas, /Cross-market posture/);
assert.doesNotMatch(atlas, /Tradier is temporarily unavailable/);
assert.doesNotMatch(atlas, /Provider status and fallback quality/);

assert.match(watchlists, /data-feature="watchlists"/);
assert.match(watchlists, /\/api\/watchlists/);
assert.match(watchlists, /Free users can keep one compact watchlist/);
assert.match(watchlists, /ravenos-explanations\.js/);
assert.match(watchlists, /ravenos-replay\.js/);

assert.match(perps, /data-feature="perps_intelligence"/);
assert.match(perps, /\/api\/hyperliquid\/perps/);
assert.match(perps, /RavenOS Perps Intelligence/);
assert.match(perps, /ravenos-participants\.js/);
assert.match(perps, /ravenos-replay\.js/);

assert.match(faq, /What is RavenOS\?/);
assert.match(faq, /Does RavenOS provide trade signals\?/);
assert.match(faq, /Flow Score is not a trade signal/);
assert.match(faq, /The goal is not prediction\. The goal is understanding\./);

assert.match(disclosures, /Last Updated: June 2026/);
assert.match(disclosures, /Not Investment Advice/);
assert.match(disclosures, /No Brokerage or Trade Execution/);
assert.match(disclosures, /Token-based access should be understood solely as a software access mechanism/);
