import {
  createDataProvenance,
  createProviderComponentHealth,
  createQuoteRequest,
  createQuoteResponse,
  createTerminalReviewPacket,
  createTransactionInspection,
  createWalletCapabilitySnapshot,
} from "./contracts.mjs";

export function freshSolanaQuoteFixture() {
  return createQuoteResponse({
    quote_id: "quote_sol_usdc_fresh",
    chain: "solana",
    quote_timestamp: "2026-06-24T19:00:00Z",
    quote_expiry: "2026-06-24T19:00:20Z",
    input_amount_base_units: "1000000000",
    expected_output_amount_base_units: "149500000",
    minimum_output_amount_base_units: "148900000",
    effective_price: "149.5",
    price_impact_bps: 42,
    provider_fee: { amount_base_units: "10000", asset: "USDC" },
    network_fee_estimate: { amount_base_units: "5000", asset: "SOL" },
    route: [
      {
        input_asset: { chain: "solana", symbol: "SOL", address: "So11111111111111111111111111111111111111112", decimals: 9 },
        output_asset: { chain: "solana", symbol: "USDC", address: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v", decimals: 6 },
        venue: "Jupiter",
        proportion_bps: 10000,
      },
    ],
    provider_provenance: createDataProvenance({
      request_id: "req_quote_1",
      build_id: "fixture-build",
      source: "Jupiter",
      source_component: "jupiter_direct_quote",
      chain: "solana",
      observed_at: "2026-06-24T19:00:00Z",
      received_at: "2026-06-24T19:00:01Z",
      expires_at: "2026-06-24T19:00:20Z",
      freshness_state: "fresh",
      age_seconds: 1,
    }),
    freshness_metadata: createDataProvenance({
      request_id: "req_quote_1",
      build_id: "fixture-build",
      source: "Jupiter",
      source_component: "jupiter_direct_quote",
      chain: "solana",
      observed_at: "2026-06-24T19:00:00Z",
      received_at: "2026-06-24T19:00:01Z",
      expires_at: "2026-06-24T19:00:20Z",
      freshness_state: "fresh",
      age_seconds: 1,
    }),
    transaction_material_available: true,
    inspection_state: "ready",
  });
}

export const ContractFixtures = Object.freeze({
  fully_fresh_quote: () => freshSolanaQuoteFixture(),
  fresh_quote_with_backfilling_evidence_provider: () => ({
    quote: freshSolanaQuoteFixture(),
    health: createProviderComponentHealth({
      component: "helius_historical_backfill",
      state: "backfilling",
      source: "Helius",
      backlog_amount: 95405,
      backlog_oldest_age_seconds: 86400,
      informational_only: true,
    }),
  }),
  recovering_ethereum_rpc: () => createProviderComponentHealth({
    component: "ethereum_rpc",
    state: "recovering",
    source: "Alchemy",
    last_success_at: "2026-06-24T18:55:00Z",
    consecutive_successes: 1,
    recovery_epoch: {
      component: "ethereum_rpc",
      outage_detected_at: "2026-06-10T00:00:00Z",
      first_recovery_success_at: "2026-06-24T18:55:00Z",
      most_recent_success_at: "2026-06-24T18:55:00Z",
      required_success_count: 3,
      current_success_count: 1,
      grace_period_seconds: 1800,
      recovery_reason: "provider_restored",
      live_tail_established: false,
      historical_backfill_complete: false,
      negative_evidence_suppressed_until: "2026-06-24T19:25:00Z",
    },
  }),
  recovering_base_rpc: () => createProviderComponentHealth({
    component: "base_rpc",
    state: "recovering",
    source: "Alchemy",
    consecutive_successes: 1,
    recovery_epoch: {
      component: "base_rpc",
      outage_detected_at: "2026-06-10T00:00:00Z",
      first_recovery_success_at: "2026-06-24T19:10:00Z",
      most_recent_success_at: "2026-06-24T19:10:00Z",
      required_success_count: 3,
      current_success_count: 1,
      grace_period_seconds: 1800,
      recovery_reason: "provider_restored",
      live_tail_established: false,
      historical_backfill_complete: false,
      negative_evidence_suppressed_until: "2026-06-24T19:40:00Z",
    },
  }),
  fresh_solana_rpc_with_helius_historical_backlog: () => ({
    solana_rpc: createProviderComponentHealth({
      component: "solana_rpc",
      state: "fresh",
      source: "Solana RPC",
      last_success_at: "2026-06-24T19:00:00Z",
      consecutive_successes: 5,
    }),
    helius_backfill: createProviderComponentHealth({
      component: "helius_historical_backfill",
      state: "backfilling",
      source: "Helius",
      backlog_amount: 95405,
      informational_only: true,
    }),
  }),
  stale_chart_data: () => createDataProvenance({
    request_id: "chart_stale_1",
    build_id: "fixture-build",
    source: "Hyperliquid",
    source_component: "market_chart_data",
    chain: "solana",
    observed_at: "2026-06-24T18:00:00Z",
    received_at: "2026-06-24T18:00:01Z",
    freshness_state: "stale",
    age_seconds: 3600,
    degraded_reason: "observation_age_exceeded",
  }),
  unavailable_transaction_simulation: () => createProviderComponentHealth({
    component: "transaction_simulation",
    state: "unavailable",
    source: "Jupiter",
    quote_review_blocking: false,
    informational_only: true,
  }),
  expired_quote: () => createQuoteResponse({
    ...freshSolanaQuoteFixture(),
    quote_id: "quote_expired",
    quote_expiry: "2026-06-24T18:59:00Z",
  }),
  malformed_provider_payload: () => ({ routePlan: "not-an-array", outAmount: null }),
  contradictory_inspection: () => createTransactionInspection({
    chain: "solana",
    transaction_format: "v0",
    quote_to_transaction_consistency_result: "mismatch",
    warnings: ["minimum_output_contradiction"],
  }),
  unknown_instruction_packet: () => createTransactionInspection({
    chain: "solana",
    transaction_format: "v0",
    unknown_instructions: [{ program: "UnknownProgram111", label: "Unverified program" }],
    quote_to_transaction_consistency_result: "unknown",
  }),
  no_wallet_connected: () => createWalletCapabilitySnapshot({
    state: "detected_not_connected",
    supported_chain: "solana",
    freshness_state: "fresh",
  }),
  quote_request_sol_to_usdc: () => createQuoteRequest({
    client_request_id: "req_sol_usdc",
    chain: "solana",
    input_asset: { chain: "solana", symbol: "SOL", address: "So11111111111111111111111111111111111111112", decimals: 9 },
    output_asset: { chain: "solana", symbol: "USDC", address: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v", decimals: 6 },
    exact_input_amount_base_units: "1000000000",
    display_amount: "1.0",
    asset_decimals: 9,
    slippage_bps: 50,
  }),
  review_packet_ready: () => createTerminalReviewPacket({
    build_id: "fixture-build",
    created_at: "2026-06-24T19:00:02Z",
    quote: freshSolanaQuoteFixture(),
    quote_expiry: "2026-06-24T19:00:20Z",
    route: freshSolanaQuoteFixture().route_legs,
    provider_provenance: freshSolanaQuoteFixture().provider_provenance,
    provider_freshness: freshSolanaQuoteFixture().freshness_metadata,
    wallet_capability_snapshot: createWalletCapabilitySnapshot({
      state: "detected_not_connected",
      supported_chain: "solana",
      freshness_state: "fresh",
    }),
    transaction_inspection: createTransactionInspection({
      chain: "solana",
      transaction_format: "v0",
      quote_to_transaction_consistency_result: "matched",
      warnings: [],
    }),
  }),
});
