// Jupiter program-to-label discovery snapshot, fetched 2026-09-07.
// Source: https://lite-api.jup.ag/swap/v1/program-id-to-label
// Routing hints only. This catalog never admits a program for execution.
export const JUPITER_VENUE_CATALOG = Object.freeze({
  "1qbkdrr3z4ryLA7pZykqxvxWPoeifcVKo6ZG9CfkvVE": "Saros DLMM",
  "2DNbzPochEcyCcWMbL4d9S3u9QqQEj5bbe6cSZFvKsbh": "BisonFi Predict",
  "2rU1oCHtQ7WJUvy15tKtFvxdYNNSc3id7AzUcjeFSddo": "VaultLiquidUnstake",
  "3TK9D8aoBFYjYZtKCjciPrVrRStsnvo7KmpcJqDavpaU": "Kipseli",
  "5U3EU2ubXtK84QcRjWVmYt9RaDyA8gKxdUrPFXmZyaki": "Virtuals",
  "5ocnV1qiCgaQR8Jb8xWnVbApfaygJ8tNoZfgPwsgx9kx": "Sanctum Infinity",
  "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8": "Raydium",
  "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P": "Pump.fun",
  "6dMXqGZ3ga2dikrYS9ovDXgHGh5RUsb2RTUj6hrQXhk6": "Stabble CLMM",
  "8ZoPDsvLWXthQaZz6aJJEWNFBZKk2ePuygi6LHT7F7Hh": "Trench",
  "9H6tua7jkLhdm3w8BvgpTn5LZNU7g4ZynDmCiNN3q6Rp": "HumidiFi",
  "9VX8EKBg6vM6tA68xaDsPkbrx26XConZjkQmhVApUptc": "TaurusFi",
  "9W959DqEETiGZocYWCQPaJ6sBmUzgfxXfqGeTEdp3aQP": "Orca V2",
  "ALPHAQmeA7bjrVuccPsYPiCvsi428SNwte66Srvs4pHA": "AlphaQ",
  "AMM55ShdkoGRB5jVYPjWziwk8m5MpwyDgsMWHaMSQWH6": "Aldrin",
  "AQU1FRd7papthgdrwPTTq5JacJh8YtwEXaBfKU3bTz45": "Aquifer",
  "Archer8kgiavM61GyusMzaaS2ft5sALtNsD1HxkUPMhy": "Archer",
  "B72M6nyCLFgWiJtAN4naUTminMiTmyGcEqQHXwVeRdht": "BinaryFi",
  "BQEJZUB4CzoT6UhRffoCkqCyqQNrCPCSGHcPEmsdbEsX": "LemmingsFi",
  "BSwp6bEBihVLdqJRKGgzjcGLHkcTuzmSo1TQkHepzH8p": "Bonkswap",
  "BiSoNHVpsVZW2F7rx2eQ59yQwKxzU5NvBcmKshCSUypi": "BisonFi",
  "Bvs46DPFxiFE6YHxLDLD6QAUcmy51FyRVPZJusPxLk3j": "Metric",
  "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK": "Raydium CLMM",
  "CLMM9tUoggJu2wagPkkqs9eFG4BWhVBZWkP1qv3Sp7tR": "Crema",
  "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C": "Raydium CP",
  "CURVEmPpijXDTNdqrA9PGP1io2rkgiVXH26xdXVGLLfz": "Trends",
  "CURVGoZn8zycx6FXwwevgBTB2gVvdbGTEpvMJDbgs2t4": "Aldrin V2",
  "CarrotwivhMpDnm27EHmRLeQ683Z1PufuqEmBZvD282s": "Carrot",
  "DEXYosS6oEGvk8uCDayvwEZz4qEyDJRf9nFgYCaqPMTm": "1DEX",
  "DNL1tgEj3nJovHw9jtyCCQD3arssCJzkmpDizknwzey4": "Denali",
  "DRVSpZ2YUYYKgZP8XtLhAGtT1zYSCKzeHfb4DgRnrgqD": "Deriverse",
  "DSwpgjMvXhtGn6BsbqmacdBZyfLj6jSWf3HJpdJtmg6N": "DexLab",
  "DecZY86MU5Gj7kppfUCEmd4LbXXuyZH1yHaP2NTqdiZB": "Saber (Decimals)",
  "DjVE6JNiYqPL2QXyCUUh8rNjHrbz9hXHNYt99MQ59qw1": "Orca V1",
  "Dooar9JkhdZ7J3LHN3A7YCuoGRUggXhQaG4kijfLGU2j": "StepN",
  "Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB": "Meteora",
  "FLUX6xBayGxLX9UcimVRxXFMHH6q43mAbRvDzSpCsvfK": "Flux",
  "FLUXubRmkEi2q6K3Y9kBPg9248ggaZVsoSFhtJHSrm1X": "FluxBeam",
  "FLiNTXPwppyoJabCoxc2uiiRygAHpmMXajiDXo2Ub1z": "Flint",
  "FUTARELBfJfQ8RDGhg1wdhddq1odMAJUePHFuBYfUxKq": "MetaDAO",
  "FW6zUqn4iKRaeopwwhwsquTY6ABWLLgjxtrC3VPnaWBf": "WhaleStreet",
  "GAMMA7meSFWaBXF25oSUgmGRwaW6sCMFLmBNiMSdbHVT": "GooseFX GAMMA",
  "Gswppe6ERWKpUTXvRPfXdzHhiCyJvLadVvXGfdpBqcE1": "Guacswap",
  "H8W3ctz92svYg6mkn1UtGfu2aQr2fnUFHM1RhScEtQDt": "Cropper",
  "HADRoNbLovyqhCsocfYQYB7QdfCAAinN9HTePvBCVDQ8": "Hadron",
  "HBVw6bZtcCaezhcBrmfyXBSBRWCdv72271xQ4GPvms2z": "Obsidian",
  "HEAVENoP2qxoeuF8Dj2oT1GHEnu49U5mJYkdeC8BAX2o": "Heaven",
  "HYEXCHtHkBagdStcJCp3xbbb9B7sdMdWXFNj6mdsG4hn": "Hylo Exchange",
  "HpNfyc2Saw7RKkQd8nEL4khUcuPhQ7WwY1B2qjx8jxFq": "PancakeSwap",
  "HumaXepHnjaRCpjYTokxY4UtaJcmx41prQ8cxGmFC5fn": "Huma",
  "HyaB3W9q6XdA5xwpU4XnSZV94htfmbmqJXZcEbRaJutt": "Invariant",
  "HysTabVUfmQBFcmzu1ctRd1Y1fxd66RBpboy1bmtDSQQ": "Hylo Stability Pool",
  "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo": "Meteora DLMM",
  "LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj": "Raydium Launchlab",
  "MERLuDFBMmsHnsBPZw2sDQZHvXFMwp8EdjudcU2HKky": "Mercurial",
  "MNFSTqtC93rEfYHB6hF82sKdZpUDFWkViLByLd1k1Ms": "Manifest",
  "MSwapi3WhNKMUGm9YrxGhypgUEt7wYQH3ZgG32XoWzH": "M Swap",
  "MoonCVVNZFSYkqNXP6bxHLPL6QQJiMagDL3qcqUQTrG": "Moonit",
  "NUMERUNsFCP3kuNmWZuXtm1AaQCPj9uw6Guv2Ekoi5P": "Perena",
  "PERPHjGBqRHArX4DySjwM6UJHiR3sWAatqfdBS2qQJu": "Perps",
  "PSwapMdSai8tjrEXcxFeQth87xC4rRsa4VA5mhGhXkP": "Penguin",
  "PhoeNiXZ8ByJGLkxNfZRnkUfjvmuYqLR89jjFHGqdXY": "Phoenix",
  "QuaNtZsgYRe5Z9Bk4LZ4cTD9tbkVoyCNf1R2BN9bBDv": "Quantum",
  "REALQqNEomY6cQGZJUGwywTBD2UmDT32rZcNnfxQ5N2": "Byreal",
  "SCALEWoRSpVZpMRqHEcDfNvBh3nUSe34jDr9r689gLa": "Scale Vmm",
  "SCALEwAvEK5gtkdHiFzXfPgtk2YwJxPDzaV3aDmR7tA": "Scale Amm",
  "SP12tWFxD9oJsVWNavTTBZvMbA6gkAmxtVgxdqvyvhY": "Sanctum",
  "SPMBzsVUuoHA4Jm6KunbsotaahvVikZs1JyTW6iJvbn": "Sanctum",
  "SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy": "Sanctum",
  "SSwapUtytfBdBn1b9NUGG6foMVPtcWgpRU32HToDUZr": "Saros",
  "SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ": "Saber",
  "SV2EYYJyRz2YhfXwXnhNAevDEui5Q6yrfyo13WtupPF": "SolFi V2",
  "SoLFiHG9TfgtdUXUjWAxi3LtvYuFyDLVhBWxdMZxyCe": "SolFi",
  "StaKE6XNKVVhG8Qu9hDJBqCW3eRe7MDGLz17nJZetLT": "XOrca",
  "SwaPpA9LAaLfeLi3a68M4DjnLqgtticKg6CnyNwgAC8": "Token Swap",
  "TessVdML9pBGgG9yGks7o4HewRaXVAMuoVj4x83GLQH": "TesseraV",
  "WooFif76YGRNjk1pA8wCsN67aQsD9f9iLsz4NcJ1AVb": "Woofi",
  "ZERor4xhbUycZ6gb9ntrhqscUcZmAbQDjEAtCf4hbZY": "ZeroFi",
  "boop8hVGQGqehUK2iVEMEnMrL5RbjywRzHKBmBE7ry4": "Boop.fun",
  "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG": "Meteora DAMM v2",
  "dbcij3LWUppWqq96dh6gJWwBifmcGfLSB5D4DuSMaqN": "Dynamic Bonding Curve",
  "endoLNCKTqDn8gSVnN2hDdpgACUPWHZTwoYnnMybpAT": "Solayer",
  "fUSioN9YKKSa3CUC2YUc4tPkHJ5Y6XW1yz8y6F7qWz9": "DefiTuna",
  "fd3nMFYTQjX1yr5ER8u7tPdHJB7qt8RpDpNtLQX2Br5": "JupiterRfqV2",
  "gatorLx9aC1e5ZWAXscv5QRKiLXnLPLXjftVc81h1Hr": "GatorSwap",
  "ghosty4ZU1Qk1HN7Ymz4pZ15QfspzJZgSYFkdKN6ZLK": "Stableswap",
  "goonuddtQRrWqqn5nFyczVKaie28f3kDkHWkHtURSLE": "GoonFi V2",
  "jup3YeL8QhtSx1e253b2FDvsMNC87fDrgQZivbrndc9": "Jupiter Lend Earn",
  "jupZ4m2GqUCJ5iueMfzQf8khFfH31d4XAQt3RzCT9Vd": "JupLend AMM",
  "obriQD1zbpyLz95G5n7nJe6a4DPjpFwa5XYPoNm113y": "Obric V2",
  "ojh19ojaKduoJZuaJADhcVGp4xt1TcdAvZmpVsCorch": "Scorch",
  "omnixgS8fnqHfCcTGKWj6JtKjzpJZ1Y5y9pyFkQDkYE": "Omnipair",
  "opnb2LAfJYbRMAHHvqjCwQxanZn7ReEHp1k81EohpZb": "OpenBook V2",
  "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA": "Pump.fun Amm",
  "pegVkBpfR9GFi5Jaa9YXAHACyM9CzCNvhc5bf8GWNyW": "Sanctum Prop S",
  "riptK81hDxhe5pW5jSzSM9iRA8azgEgLJ4dXkPtBS7j": "Riptide",
  "runnrXXdsSRkdueCRYxKDvSWfv6nAnrG5dcM29qj1HA": "RunnerRodeo",
  "save8RQVPMWNTzU18t3GBvBkN9hT7jsGjiCQ28FpD9H": "Perena Star V2",
  "so1f7APRw5pJ5iNJrM9g5X9tQgXzk8kMUnXxDNdt99b": "Sanctum SOLS",
  "srAMMzfVHVAtgSJc8iH6CfKzuWuUTzLHVCE81QU1rgi": "Gavel",
  "stkitrT1Uoy18Dk1fTrgPw8W6MVzoCfYoAFT4MLsmhq": "Sanctum",
  "swapFpHZwjELNnjvThjajtiVmkz3yPQEHjLtka2fwHW": "Stabble Weighted Swap",
  "swapNyd8XiQwJ6ianp9snpu4brUqFxadzvHebnAXjJZ": "Stabble Stable Swap",
  "treaf4wWBBty3fHdyBpo35Mz84M8k3heKXmjmi9vFt5": "Helium Network",
  "vVoLTRjQmtFpiYoegx285Ze4gsLJ8ZxgFKVcuvmG1a8": "Voltr",
  "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc": "Whirlpool"
});
