export const ATLAS_FREE_SOURCE_REGISTRY_SCHEMA = "ravenos.atlas_free_sources.v1";
export const ATLAS_FREE_SOURCE_REGISTRY_REVIEWED_AT = "2026-08-26";

const SOURCES = Object.freeze([
  Object.freeze({
    source_id: "sec_edgar",
    provider: "U.S. Securities and Exchange Commission",
    role: "company_filings_fundamentals_and_events",
    products: Object.freeze(["submissions", "companyfacts", "xbrl_frames", "forms_3_4_5", "schedules_13d_13g", "form_13f", "form_n_port", "form_n_cen", "structured_disclosure_rss"]),
    transports: Object.freeze(["https_json", "rss", "bulk_zip"]),
    cadence: "real_time_api_and_ten_minute_rss",
    activation_state: "connected_via_atlas_origin",
    current_surfaces: Object.freeze(["filings", "insider_filings"]),
    next_surfaces: Object.freeze(["company_fundamentals", "filing_event_stream", "institutional_holdings", "delayed_fund_holdings"]),
    data_fee_usd_monthly: 0,
    key_required: false,
    public_display_posture: "eligible_subject_to_sec_fair_access",
    attribution: "Source: U.S. Securities and Exchange Commission",
    evidence_url: "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
    operating_constraint: "server_side_only_with_declared_user_agent_and_sec_fair_access_limits",
  }),
  Object.freeze({
    source_id: "eia_open_data",
    provider: "U.S. Energy Information Administration",
    role: "energy_fundamentals",
    products: Object.freeze(["electricity", "petroleum", "natural_gas", "coal", "energy_forecasts"]),
    transports: Object.freeze(["https_json", "bulk_download"]),
    cadence: "product_specific",
    activation_state: "connected_via_atlas_origin",
    current_surfaces: Object.freeze(["facets", "series"]),
    next_surfaces: Object.freeze(["energy_event_context"]),
    data_fee_usd_monthly: 0,
    key_required: true,
    public_display_posture: "eligible_with_eia_terms_and_attribution",
    attribution: "Source: U.S. Energy Information Administration (EIA)",
    evidence_url: "https://www.eia.gov/opendata/documentation.php",
    operating_constraint: "keep_the_free_api_key_server_side_and_do_not_imply_eia_endorsement",
  }),
  Object.freeze({
    source_id: "openfigi_v3",
    provider: "OpenFIGI",
    role: "provider_independent_security_master",
    products: Object.freeze(["figi_identifier", "identifier_mapping", "instrument_search", "listing_metadata"]),
    transports: Object.freeze(["https_json"]),
    cadence: "on_demand_with_cached_mappings",
    activation_state: "ready_for_origin_adapter",
    current_surfaces: Object.freeze([]),
    next_surfaces: Object.freeze(["canonical_instrument_identity", "cross_provider_identifier_mapping"]),
    data_fee_usd_monthly: 0,
    key_required: false,
    public_display_posture: "figi_identifiers_public_domain_and_commercially_redistributable",
    attribution: "Instrument identity mapped with OpenFIGI",
    evidence_url: "https://www.openfigi.com/docs/terms-of-service",
    operating_constraint: "use_v3_respect_rate_limits_and_do_not_treat_third_party_input_identifiers_as_relicensed",
  }),
  Object.freeze({
    source_id: "treasury_daily_rates",
    provider: "U.S. Department of the Treasury",
    role: "treasury_yield_curves_and_bill_rates",
    products: Object.freeze(["nominal_yield_curve", "real_yield_curve", "bill_rates", "long_term_rates"]),
    transports: Object.freeze(["https_xml", "csv"]),
    cadence: "daily",
    activation_state: "ready_for_origin_adapter",
    current_surfaces: Object.freeze([]),
    next_surfaces: Object.freeze(["rates_curve", "real_rates", "curve_regime"]),
    data_fee_usd_monthly: 0,
    key_required: false,
    public_display_posture: "eligible_after_route_policy_is_recorded",
    attribution: "Source: U.S. Department of the Treasury",
    evidence_url: "https://home.treasury.gov/treasury-daily-interest-rate-xml-feed",
    operating_constraint: "poll_and_cache_in_the_private_origin",
  }),
  Object.freeze({
    source_id: "new_york_fed_reference_rates",
    provider: "Federal Reserve Bank of New York",
    role: "official_reference_rates",
    products: Object.freeze(["sofr", "sofr_averages", "sofr_index", "effr", "obfr", "tgcr", "bgcr"]),
    transports: Object.freeze(["https_json", "csv"]),
    cadence: "business_daily",
    activation_state: "ready_for_origin_adapter",
    current_surfaces: Object.freeze([]),
    next_surfaces: Object.freeze(["policy_rates", "funding_conditions"]),
    data_fee_usd_monthly: 0,
    key_required: false,
    public_display_posture: "eligible_after_route_policy_is_recorded",
    attribution: "Source: Federal Reserve Bank of New York",
    evidence_url: "https://www.newyorkfed.org/markets/reference-rates",
    operating_constraint: "use_the_official_markets_data_api_and_preserve_rate_labels",
  }),
  Object.freeze({
    source_id: "ecb_reference_fx",
    provider: "European Central Bank",
    role: "daily_foreign_exchange_reference_rates",
    products: Object.freeze(["euro_reference_exchange_rates", "bilateral_exchange_rate_history"]),
    transports: Object.freeze(["https_sdmx", "xml", "csv", "rss"]),
    cadence: "business_daily",
    activation_state: "ready_for_origin_adapter",
    current_surfaces: Object.freeze([]),
    next_surfaces: Object.freeze(["daily_fx_reference", "fx_regime_context"]),
    data_fee_usd_monthly: 0,
    key_required: false,
    public_display_posture: "commercial_reuse_allowed_with_source_attribution",
    attribution: "Source: ECB statistics",
    evidence_url: "https://www.ecb.europa.eu/stats/ecb_statistics/governance_and_quality_framework/html/usage_policy.en.html",
    operating_constraint: "reference_only_not_for_transaction_pricing_and_label_any_raven_modifications",
  }),
  Object.freeze({
    source_id: "bls_public_data",
    provider: "U.S. Bureau of Labor Statistics",
    role: "labor_and_inflation_statistics",
    products: Object.freeze(["cpi", "ppi", "employment", "wages", "productivity"]),
    transports: Object.freeze(["https_json", "public_download"]),
    cadence: "release_calendar",
    activation_state: "ready_for_origin_adapter",
    current_surfaces: Object.freeze([]),
    next_surfaces: Object.freeze(["inflation_context", "labor_context", "macro_release_events"]),
    data_fee_usd_monthly: 0,
    key_required: false,
    public_display_posture: "eligible_after_route_policy_is_recorded",
    attribution: "Source: U.S. Bureau of Labor Statistics",
    evidence_url: "https://www.bls.gov/developers/",
    operating_constraint: "respect_unregistered_and_registered_api_request_limits",
  }),
  Object.freeze({
    source_id: "bea_public_data",
    provider: "U.S. Bureau of Economic Analysis",
    role: "national_and_regional_accounts",
    products: Object.freeze(["gdp", "personal_income", "corporate_profits", "international_trade", "regional_accounts"]),
    transports: Object.freeze(["https_json"]),
    cadence: "release_calendar",
    activation_state: "ready_for_origin_adapter",
    current_surfaces: Object.freeze([]),
    next_surfaces: Object.freeze(["growth_context", "income_context", "macro_release_events"]),
    data_fee_usd_monthly: 0,
    key_required: true,
    public_display_posture: "eligible_after_route_policy_is_recorded",
    attribution: "Source: U.S. Bureau of Economic Analysis",
    evidence_url: "https://apps.bea.gov/api/",
    operating_constraint: "keep_the_free_api_key_server_side",
  }),
  Object.freeze({
    source_id: "cftc_cot",
    provider: "U.S. Commodity Futures Trading Commission",
    role: "futures_positioning",
    products: Object.freeze(["legacy_cot", "disaggregated_cot", "traders_in_financial_futures", "futures_and_options_combined"]),
    transports: Object.freeze(["https_json", "csv", "rss", "bulk_download"]),
    cadence: "weekly",
    activation_state: "ready_for_origin_adapter",
    current_surfaces: Object.freeze([]),
    next_surfaces: Object.freeze(["futures_positioning", "crowding_context"]),
    data_fee_usd_monthly: 0,
    key_required: false,
    public_display_posture: "eligible_after_route_policy_is_recorded",
    attribution: "Source: U.S. Commodity Futures Trading Commission",
    evidence_url: "https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm",
    operating_constraint: "aggregate_positioning_only_not_contract_quotes",
  }),
  Object.freeze({
    source_id: "iex_hist",
    provider: "IEX Exchange",
    role: "us_equity_t_plus_one_reference_data",
    products: Object.freeze(["tops_hist", "deep_hist"]),
    transports: Object.freeze(["pcap_download"]),
    cadence: "t_plus_one",
    activation_state: "ready_for_private_ingestion_pipeline",
    current_surfaces: Object.freeze([]),
    next_surfaces: Object.freeze(["equity_end_of_day_reference", "iex_volume_and_trade_context"]),
    data_fee_usd_monthly: 0,
    key_required: false,
    public_display_posture: "distribution_allowed_with_exact_iex_attribution",
    attribution: "Data provided for free by IEX. By accessing or using IEX Historical Data, you agree to the IEX Historical Data Terms of Use.",
    evidence_url: "https://www.iex.io/legal/hist-data-terms",
    operating_constraint: "iex_exchange_only_not_consolidated_and_not_a_trading_price_basis",
  }),
  Object.freeze({
    source_id: "iex_tops_delayed",
    provider: "IEX Exchange",
    role: "delayed_us_equity_top_of_book_and_last_sale",
    products: Object.freeze(["tops_delayed"]),
    transports: Object.freeze(["iex_tp_multicast_or_approved_distributor"]),
    cadence: "at_least_fifteen_minutes_delayed",
    activation_state: "agreement_and_connectivity_required",
    current_surfaces: Object.freeze([]),
    next_surfaces: Object.freeze(["delayed_equity_quotes"]),
    data_fee_usd_monthly: 0,
    key_required: false,
    public_display_posture: "redistribution_defined_but_feed_access_must_be_established",
    attribution: "Source: IEX Exchange; delayed at least 15 minutes; IEX-only market activity",
    evidence_url: "https://www.iex.io/resources/trading/fee-schedule",
    operating_constraint: "not_an_http_api_and_connectivity_or_distributor_costs_may_apply",
  }),
  Object.freeze({
    source_id: "options_broker_overlay",
    provider: "User-connected broker",
    role: "current_options_quotes_and_chains",
    products: Object.freeze(["option_expirations", "option_chain", "option_quotes"]),
    transports: Object.freeze(["authenticated_server_side_broker_api"]),
    cadence: "broker_entitlement_dependent",
    activation_state: "authenticated_user_overlay_only",
    current_surfaces: Object.freeze([]),
    next_surfaces: Object.freeze(["private_current_options_overlay"]),
    data_fee_usd_monthly: null,
    key_required: false,
    public_display_posture: "not_for_anonymous_public_redistribution",
    attribution: "Shown only to the connected and entitled account holder",
    evidence_url: "https://www.opraplan.com/",
    operating_constraint: "broker_data_cost_and_availability_depend_on_the_users_entitlement_never_cache_or_project_quotes_into_the_anonymous_public_feed",
  }),
]);

const BLOCKED_PRODUCTS = Object.freeze([
  Object.freeze({
    product_id: "anonymous_delayed_options_quotes",
    state: "blocked_without_opra_vendor_rights",
    reason: "a_fifteen_minute_delay_removes_some_usage_fees_but_does_not_remove_the_opra_vendor_agreement_requirement",
    public_fallback: "contract_identity_and_education_only",
    authenticated_fallback: "user_connected_broker_overlay",
    evidence_url: "https://www.opraplan.com/",
  }),
  Object.freeze({
    product_id: "fred_ice_bofa_series",
    state: "blocked_without_preapproval",
    reason: "fred_is_a_delivery_channel_not_blanket_commercial_redistribution_permission_for_third_party_series",
    public_fallback: "use_direct_us_agency_series_where_an_equivalent_exists",
    authenticated_fallback: null,
    evidence_url: "https://fred.stlouisfed.org/legal/",
  }),
]);

export function buildAtlasFreeSourceRegistry() {
  return {
    ok: true,
    safe_public: true,
    schema_version: ATLAS_FREE_SOURCE_REGISTRY_SCHEMA,
    reviewed_at: ATLAS_FREE_SOURCE_REGISTRY_REVIEWED_AT,
    strategy: "free_authoritative_sources_first_with_broker_private_options",
    sources: SOURCES.map((source) => ({
      ...source,
      products: [...source.products],
      transports: [...source.transports],
      current_surfaces: [...source.current_surfaces],
      next_surfaces: [...source.next_surfaces],
    })),
    blocked_products: BLOCKED_PRODUCTS.map((product) => ({ ...product })),
    guardrails: {
      provider_key_never_equals_public_display_permission: true,
      observations_require_recorded_product_level_rights: true,
      anonymous_options_quotes_require_opra_vendor_rights: true,
      broker_quotes_are_private_to_the_entitled_user: true,
      iex_data_is_iex_only_not_consolidated: true,
      credentials_stay_server_side: true,
    },
  };
}
