// Public release switches only. Credentials and resource bindings stay separate.
export const RELEASE_FLAGS_BINDING = "RAVENOS_RELEASE_FLAGS";
const flagNames = new Set([
  "LIVE_SHIELDED_EXECUTION_ENABLED",
  "RAVENOS_AFFILIATE_COMMISSIONS_ENABLED",
  "RAVENOS_AFFILIATE_ENROLLMENT_ENABLED",
  "RAVENOS_AFFILIATE_PAYOUTS_ENABLED",
  "RAVENOS_AFFILIATE_PUBLIC_PROFILE_CTA_ENABLED",
  "RAVENOS_AGENTIC_PAPER_ENABLED",
  "RAVENOS_ALCHEMY_WALLET_HISTORY_ENABLED",
  "RAVENOS_COINGECKO_ENABLED",
  "RAVENOS_COMMUNITY_ENABLED",
  "RAVENOS_COPY_FEE_COLLECTION_ENABLED",
  "RAVENOS_CUSTOMER_ACCOUNTS_ENABLE",
  "RAVENOS_DEXCH_CHARTS_ENABLED",
  "RAVENOS_DEXCH_COMMERCIAL_USE_ACKNOWLEDGED",
  "RAVENOS_DEXCH_DISCOVERY_ENABLED",
  "RAVENOS_DEXSCREENER_CHARTS_ENABLED",
  "RAVENOS_ENTITLEMENT_RESOLUTION_ENABLE",
  "RAVENOS_EVM_WALLET_BACKFILL_ENABLED",
  "RAVENOS_EVM_WALLET_LOOKUP_ENABLED",
  "RAVENOS_EVM_WALLET_RECONSTRUCTION_ENABLED",
  "RAVENOS_HELIUS_WALLET_HISTORY_ENABLED",
  "RAVENOS_LEGAL_ACCEPTANCE_ENABLED",
  "RAVENOS_LEGAL_COUNSEL_APPROVED",
  "RAVENOS_LIVE_COPY_ENABLED",
  "RAVENOS_MARKET_PROVIDER_FALLBACKS_ENABLED",
  "RAVENOS_ONCHAIN_CHART_PRODUCTION_QUALIFIED",
  "RAVENOS_PARTICIPATION_UNIVERSE_ENABLED",
  "RAVENOS_PRIVY_DEFAULT_WALLET_ONBOARDING",
  "RAVENOS_PRIVY_DELEGATED_SIGNING_ENABLED",
  "RAVENOS_PRIVY_ENABLED",
  "RAVENOS_PRIVY_EVM_ENABLED",
  "RAVENOS_PRIVY_MANUAL_SIGNING_ENABLED",
  "RAVENOS_PRIVY_SOLANA_ENABLED",
  "RAVENOS_PRIVY_WALLETS_ENABLED",
  "RAVENOS_PRO_ACCOUNT_BILLING_ENABLED",
  "RAVENOS_PRO_CASHBACK_AUTO_APPLY_ENABLED",
  "RAVENOS_PRO_CASHBACK_CLAIMS_ENABLED",
  "RAVENOS_PRO_CASHBACK_ENABLED",
  "RAVENOS_PRO_CASHBACK_SUBSCRIPTION_CREDIT_ENABLED",
  "RAVENOS_PRO_FREE_TRIAL_ENABLED",
  "RAVENOS_PRO_INTELLIGENCE_ROUTES_ENABLE",
  "RAVENOS_PRO_PARTICIPANT_ADVANCED_ENABLE",
  "RAVENOS_PRO_PERPS_ADVANCED_ENABLE",
  "RAVENOS_PUBLIC_EVM_HOLDERS_ENABLED",
  "RAVENOS_PUBLIC_PROJECTION_SPLIT_ENABLE",
  "RAVENOS_PUBLIC_ROUTE_RESPONSE_CACHE_ENABLED",
  "RAVENOS_PUBLIC_SOLANA_HOLDERS_ENABLED",
  "RAVENOS_REFERRALS_ENABLED",
  "RAVENOS_REFERRAL_BILLING_RECONCILIATION_ENABLED",
  "RAVENOS_SHADOW_COPY_ENABLED",
  "RAVENOS_SHADOW_LEDGER_ENABLED",
  "RAVENOS_WALLET_BACKFILL_ENABLED",
  "RAVENOS_WALLET_COPYABILITY_CHECKPOINTS_ENABLED",
  "RAVENOS_WALLET_COPYABILITY_PROBES_ENABLED",
  "RAVENOS_WALLET_COPY_ROUTES_ENABLED",
  "RAVENOS_WALLET_DEX_MARKS_ENABLED",
  "RAVENOS_WALLET_HISTORICAL_USD_ENABLED",
  "RAVENOS_WALLET_HOLDER_CONTEXT_ENABLED",
  "RAVENOS_WALLET_INGESTION_ENABLED",
  "RAVENOS_WALLET_INTELLIGENCE_ENABLED",
  "RAVENOS_WALLET_MARKET_EVIDENCE_ENABLED",
  "RAVENOS_WALLET_OBSERVER_ENABLED",
  "RAVENOS_WALLET_OBSERVER_EVALUATOR_ENABLED",
  "RAVENOS_WALLET_PRIORITY_WARMUP_ENABLED",
  "RAVENOS_WALLET_PUBLIC_LISTS_ENABLED",
  "RAVENOS_WALLET_RPC_POLL_ENABLED",
  "RAVENOS_WALLET_SCREENER_ENABLED",
  "RAVENOS_WALLET_UNIVERSE_ENABLED",
  "SHIELDED_DEPLOY_ENABLED",
  "SHIELDED_RESERVE_ENABLED",
  "SHIELDED_RETURN_ENABLED",
  "SHIELDED_ROUTE_QUOTES_ENABLED",
  "SHIELDED_SEND_ENABLED",
  "ZCASH_ENABLED"
]);

function validateFlags(value) {
  let flags = value;
  if (typeof flags === "string") {
    try { flags = JSON.parse(flags); } catch { throw new Error("Invalid release flags"); }
  }
  if (!flags || Array.isArray(flags) || typeof flags !== "object") throw new Error("Invalid release flags");
  if (JSON.stringify(flags).length > 5000) throw new Error("Release flags exceed binding limit");
  for (const [key, flag] of Object.entries(flags)) {
    if (!flagNames.has(key) || (flag !== "0" && flag !== "1")) throw new Error("Invalid release flags");
  }
  return flags;
}

export function packReleaseFlags(vars) {
  if (Object.hasOwn(vars, RELEASE_FLAGS_BINDING)) throw new Error("Release flags already packed");
  const bindings = { ...vars }, flags = {};
  for (const name of flagNames) {
    if (!Object.hasOwn(bindings, name)) continue;
    flags[name] = bindings[name];
    delete bindings[name];
  }
  return { ...bindings, [RELEASE_FLAGS_BINDING]: validateFlags(flags) };
}

export function resolveReleaseFlags(env = {}) {
  if (!Object.hasOwn(env, RELEASE_FLAGS_BINDING)) return env;
  // Explicit operator overrides take precedence. Preserve binding objects by reference.
  return { ...validateFlags(env[RELEASE_FLAGS_BINDING]), ...env };
}

export function assertReleaseBindingPreservation(existingBindings, vars) {
  const effective = resolveReleaseFlags(vars);
  const missing = existingBindings.filter(binding =>
    ["plain_text", "json"].includes(binding.type) && !Object.hasOwn(effective, binding.name));
  if (missing.length) throw new Error("Release would drop existing configuration: " + missing.map(x => x.name).join(", "));
}

